# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QGraphicsView, QGridLayout, QHBoxLayout, QLabel,
    QLayout, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QTextEdit, QWidget)

class Ui_FeatureFinder(object):
    def setupUi(self, FeatureFinder):
        if not FeatureFinder.objectName():
            FeatureFinder.setObjectName(u"Feature Finder")
        FeatureFinder.resize(961, 431)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FeatureFinder.sizePolicy().hasHeightForWidth())
        FeatureFinder.setSizePolicy(sizePolicy)
        FeatureFinder.setMinimumSize(QSize(961, 431))
        self.gridLayout_2 = QGridLayout(FeatureFinder)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.stream_window = QGraphicsView(FeatureFinder)
        self.stream_window.setObjectName(u"stream_window")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.stream_window.sizePolicy().hasHeightForWidth())
        self.stream_window.setSizePolicy(sizePolicy1)
        self.stream_window.setMinimumSize(QSize(471, 411))
        self.stream_window.setFocusPolicy(Qt.NoFocus)

        self.gridLayout_2.addWidget(self.stream_window, 0, 2, 1, 1)

        self.frame = QFrame(FeatureFinder)
        self.frame.setObjectName(u"frame")
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMinimumSize(QSize(466, 413))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.image_paths_header = QLabel(self.frame)
        self.image_paths_header.setObjectName(u"image_paths_header")
        self.image_paths_header.setGeometry(QRect(10, 10, 441, 24))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.image_paths_header.sizePolicy().hasHeightForWidth())
        self.image_paths_header.setSizePolicy(sizePolicy2)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.image_paths_header.setFont(font)
        self.image_paths_header.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.file_path_label = QLabel(self.frame)
        self.file_path_label.setObjectName(u"file_path_label")
        self.file_path_label.setGeometry(QRect(10, 40, 101, 24))
        self.file_path_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.file_path_entry = QTextEdit(self.frame)
        self.file_path_entry.setObjectName(u"file_path_entry")
        self.file_path_entry.setGeometry(QRect(120, 40, 241, 41))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.file_path_entry.sizePolicy().hasHeightForWidth())
        self.file_path_entry.setSizePolicy(sizePolicy3)
        self.file_path_entry.setFrameShape(QFrame.StyledPanel)
        self.file_path_entry.setFrameShadow(QFrame.Plain)
        self.file_path_entry.setLineWidth(1)
        self.file_path_entry.setMidLineWidth(0)
        self.file_path_entry.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.file_path_entry.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.file_path_entry.setLineWrapMode(QTextEdit.NoWrap)
        self.file_path_browse_button = QPushButton(self.frame)
        self.file_path_browse_button.setObjectName(u"file_path_browse_button")
        self.file_path_browse_button.setGeometry(QRect(370, 40, 81, 24))
        self.save_image_button = QPushButton(self.frame)
        self.save_image_button.setObjectName(u"save_image_button")
        self.save_image_button.setGeometry(QRect(120, 90, 81, 24))
        self.file_path_label_2 = QLabel(self.frame)
        self.file_path_label_2.setObjectName(u"file_path_label_2")
        self.file_path_label_2.setGeometry(QRect(10, 90, 101, 24))
        self.file_path_label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.detection_controls_header = QLabel(self.frame)
        self.detection_controls_header.setObjectName(u"detection_controls_header")
        self.detection_controls_header.setGeometry(QRect(10, 140, 441, 24))
        sizePolicy2.setHeightForWidth(self.detection_controls_header.sizePolicy().hasHeightForWidth())
        self.detection_controls_header.setSizePolicy(sizePolicy2)
        self.detection_controls_header.setFont(font)
        self.detection_controls_header.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.rect_detection_label = QLabel(self.frame)
        self.rect_detection_label.setObjectName(u"rect_detection_label")
        self.rect_detection_label.setGeometry(QRect(10, 170, 101, 24))
        self.rect_detection_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.crosshair_detection_check = QCheckBox(self.frame)
        self.crosshair_detection_check.setObjectName(u"crosshair_detection_check")
        self.crosshair_detection_check.setGeometry(QRect(120, 170, 201, 24))
        self.crosshair_detection_check.setChecked(True)
        self.threshold_label = QLabel(self.frame)
        self.threshold_label.setObjectName(u"threshold_label")
        self.threshold_label.setGeometry(QRect(10, 200, 101, 24))
        self.threshold_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.threshold_slider = QSlider(self.frame)
        self.threshold_slider.setObjectName(u"threshold_slider")
        self.threshold_slider.setGeometry(QRect(120, 200, 241, 24))
        self.threshold_slider.setMaximum(255)
        self.threshold_slider.setSingleStep(1)
        self.threshold_slider.setOrientation(Qt.Horizontal)
        self.threshold_slider.setTickPosition(QSlider.TicksBelow)
        self.threshold_slider.setTickInterval(5)
        self.threshold_spin = QSpinBox(self.frame)
        self.threshold_spin.setObjectName(u"threshold_spin")
        self.threshold_spin.setGeometry(QRect(370, 200, 81, 24))
        self.threshold_spin.setMaximum(255)
        self.threshold_spin.setSingleStep(1)
        self.gauss_blur_label = QLabel(self.frame)
        self.gauss_blur_label.setObjectName(u"gauss_blur_label")
        self.gauss_blur_label.setGeometry(QRect(10, 230, 101, 24))
        self.gauss_blur_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.gauss_blur_slider = QSlider(self.frame)
        self.gauss_blur_slider.setObjectName(u"gauss_blur_slider")
        self.gauss_blur_slider.setGeometry(QRect(120, 234, 241, 24))
        self.gauss_blur_slider.setMaximum(500)
        self.gauss_blur_slider.setSingleStep(1)
        self.gauss_blur_slider.setValue(1)
        self.gauss_blur_slider.setOrientation(Qt.Horizontal)
        self.gauss_blur_slider.setTickPosition(QSlider.TicksBelow)
        self.gauss_blur_slider.setTickInterval(25)
        self.gauss_blur_spin = QSpinBox(self.frame)
        self.gauss_blur_spin.setObjectName(u"gauss_blur_spin")
        self.gauss_blur_spin.setGeometry(QRect(370, 230, 81, 24))
        self.gauss_blur_spin.setMaximum(500)
        self.gauss_blur_spin.setSingleStep(1)
        self.feature_size_label = QLabel(self.frame)
        self.feature_size_label.setObjectName(u"feature_size_label")
        self.feature_size_label.setGeometry(QRect(10, 260, 101, 24))
        self.feature_size_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.horizontalLayoutWidget_2 = QWidget(self.frame)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(120, 261, 241, 20))
        self.feature_size_range_slider = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.feature_size_range_slider.setObjectName(u"feature_size_range_slider")
        self.feature_size_range_slider.setContentsMargins(0, 0, 0, 0)
        self.feature_size_min = QLabel(self.frame)
        self.feature_size_min.setObjectName(u"feature_size_min")
        self.feature_size_min.setGeometry(QRect(120, 280, 101, 14))
        font1 = QFont()
        font1.setPointSize(7)
        self.feature_size_min.setFont(font1)
        self.feature_size_max = QLabel(self.frame)
        self.feature_size_max.setObjectName(u"feature_size_max")
        self.feature_size_max.setGeometry(QRect(260, 280, 101, 14))
        self.feature_size_max.setFont(font1)
        self.feature_size_max.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.detection_controls_header_2 = QLabel(self.frame)
        self.detection_controls_header_2.setObjectName(u"detection_controls_header_2")
        self.detection_controls_header_2.setGeometry(QRect(10, 300, 441, 24))
        sizePolicy2.setHeightForWidth(self.detection_controls_header_2.sizePolicy().hasHeightForWidth())
        self.detection_controls_header_2.setSizePolicy(sizePolicy2)
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(False)
        self.detection_controls_header_2.setFont(font2)
        self.detection_controls_header_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.circularity_label = QLabel(self.frame)
        self.circularity_label.setObjectName(u"circularity_label")
        self.circularity_label.setGeometry(QRect(10, 330, 101, 24))
        self.circularity_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.circularity_slider = QSlider(self.frame)
        self.circularity_slider.setObjectName(u"circularity_slider")
        self.circularity_slider.setGeometry(QRect(120, 330, 241, 24))
        self.circularity_slider.setMinimum(10)
        self.circularity_slider.setMaximum(100)
        self.circularity_slider.setSingleStep(1)
        self.circularity_slider.setOrientation(Qt.Horizontal)
        self.circularity_slider.setTickPosition(QSlider.TicksBelow)
        self.circularity_slider.setTickInterval(5)
        self.circularity_spin = QDoubleSpinBox(self.frame)
        self.circularity_spin.setObjectName(u"circularity_spin")
        self.circularity_spin.setGeometry(QRect(370, 330, 81, 24))
        self.circularity_spin.setMinimum(0.100000000000000)
        self.circularity_spin.setMaximum(1.000000000000000)
        self.circularity_spin.setSingleStep(0.100000000000000)
        self.blob_size_label = QLabel(self.frame)
        self.blob_size_label.setObjectName(u"blob_size_label")
        self.blob_size_label.setGeometry(QRect(10, 360, 101, 24))
        self.blob_size_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.horizontalLayoutWidget = QWidget(self.frame)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(120, 361, 241, 20))
        self.blob_size_range_slider = QHBoxLayout(self.horizontalLayoutWidget)
        self.blob_size_range_slider.setObjectName(u"blob_size_range_slider")
        self.blob_size_range_slider.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.blob_size_range_slider.setContentsMargins(0, 0, 0, 0)
        self.blob_size_min = QLabel(self.frame)
        self.blob_size_min.setObjectName(u"blob_size_min")
        self.blob_size_min.setGeometry(QRect(120, 380, 101, 14))
        self.blob_size_min.setFont(font1)
        self.blob_size_max = QLabel(self.frame)
        self.blob_size_max.setObjectName(u"blob_size_max")
        self.blob_size_max.setGeometry(QRect(260, 380, 101, 14))
        self.blob_size_max.setFont(font1)
        self.blob_size_max.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.frame, 0, 3, 1, 1)


        self.retranslateUi(FeatureFinder)

        QMetaObject.connectSlotsByName(FeatureFinder)
    # setupUi

    def retranslateUi(self, FeatureFinder):
        FeatureFinder.setWindowTitle(QCoreApplication.translate("Feature Finder", u"Feature Finder", None))
        self.image_paths_header.setText(QCoreApplication.translate("Feature Finder", u"Image Import/Export", None))
        self.file_path_label.setText(QCoreApplication.translate("Feature Finder", u"Input File Path:", None))
#if QT_CONFIG(tooltip)
        self.file_path_entry.setToolTip(QCoreApplication.translate("Feature Finder", u"Path to input file ", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.file_path_browse_button.setToolTip(QCoreApplication.translate("Feature Finder", u"Path browser for input file ", None))
#endif // QT_CONFIG(tooltip)
        self.file_path_browse_button.setText(QCoreApplication.translate("Feature Finder", u"Browse...", None))
#if QT_CONFIG(tooltip)
        self.save_image_button.setToolTip(QCoreApplication.translate("Feature Finder", u"Save the displayed image to provided path", None))
#endif // QT_CONFIG(tooltip)
        self.save_image_button.setText(QCoreApplication.translate("Feature Finder", u"Save to File...", None))
        self.file_path_label_2.setText(QCoreApplication.translate("Feature Finder", u"Export drawing:", None))
        self.detection_controls_header.setText(QCoreApplication.translate("Feature Finder", u"Detection Controls", None))
        self.rect_detection_label.setText(QCoreApplication.translate("Feature Finder", u"Rect. Detection:", None))
#if QT_CONFIG(tooltip)
        self.crosshair_detection_check.setToolTip(QCoreApplication.translate("Feature Finder", u"Turning OFF rect. detection will toggle ON crosshair detection", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_detection_check.setText(QCoreApplication.translate("Feature Finder", u"On / Off (Crosshair Detection)", None))
        self.threshold_label.setText(QCoreApplication.translate("Feature Finder", u"Pixel Threshold:", None))
#if QT_CONFIG(tooltip)
        self.threshold_slider.setToolTip(QCoreApplication.translate("Feature Finder", u"Threshold value for edge detection", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.threshold_spin.setToolTip(QCoreApplication.translate("Feature Finder", u"Threshold value for edge detection", None))
#endif // QT_CONFIG(tooltip)
        self.gauss_blur_label.setText(QCoreApplication.translate("Feature Finder", u"Gaussian Blur:", None))
#if QT_CONFIG(tooltip)
        self.gauss_blur_slider.setToolTip(QCoreApplication.translate("Feature Finder", u"Gaussian blur kernel size", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.gauss_blur_spin.setToolTip(QCoreApplication.translate("Feature Finder", u"Gaussian blur kernel size", None))
#endif // QT_CONFIG(tooltip)
        self.feature_size_label.setText(QCoreApplication.translate("Feature Finder", u"Size Range:", None))
        self.feature_size_min.setText(QCoreApplication.translate("Feature Finder", u"0", None))
        self.feature_size_max.setText(QCoreApplication.translate("Feature Finder", u"0", None))
        self.detection_controls_header_2.setText(QCoreApplication.translate("Feature Finder", u"Blob-Specific Controls...", None))
        self.circularity_label.setText(QCoreApplication.translate("Feature Finder", u"Circularity:", None))
#if QT_CONFIG(tooltip)
        self.circularity_slider.setToolTip(QCoreApplication.translate("Feature Finder", u"The closer to 1, the more \"perfect\" the circle is", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.circularity_spin.setToolTip(QCoreApplication.translate("Feature Finder", u"The closer to 1, the more \"perfect\" the circle is", None))
#endif // QT_CONFIG(tooltip)
        self.blob_size_label.setText(QCoreApplication.translate("Feature Finder", u"Size Range:", None))
        self.blob_size_min.setText(QCoreApplication.translate("Feature Finder", u"0", None))
        self.blob_size_max.setText(QCoreApplication.translate("Feature Finder", u"0", None))
    # retranslateUi

