# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QGraphicsView, QGridLayout, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QWidget)

class Ui_featureFinder(object):
    def setupUi(self, featureFinder):
        if not featureFinder.objectName():
            featureFinder.setObjectName(u"featureFinder")
        featureFinder.resize(1233, 758)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(featureFinder.sizePolicy().hasHeightForWidth())
        featureFinder.setSizePolicy(sizePolicy)
        featureFinder.setMinimumSize(QSize(0, 0))
        featureFinder.setMaximumSize(QSize(16777215, 16777215))
        self.gridLayout_2 = QGridLayout(featureFinder)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.feature_fitting_frame = QFrame(featureFinder)
        self.feature_fitting_frame.setObjectName(u"feature_fitting_frame")
        self.feature_fitting_frame.setEnabled(False)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.feature_fitting_frame.sizePolicy().hasHeightForWidth())
        self.feature_fitting_frame.setSizePolicy(sizePolicy1)
        self.feature_fitting_frame.setMaximumSize(QSize(1000, 16777215))
        self.feature_fitting_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.feature_fitting_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout = QGridLayout(self.feature_fitting_frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.fitting_tabs = QTabWidget(self.feature_fitting_frame)
        self.fitting_tabs.setObjectName(u"fitting_tabs")
        self.fitting_tabs.setEnabled(False)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.fitting_tabs.sizePolicy().hasHeightForWidth())
        self.fitting_tabs.setSizePolicy(sizePolicy2)
        font = QFont()
        font.setPointSize(9)
        self.fitting_tabs.setFont(font)
        self.crosshair_tab = QWidget()
        self.crosshair_tab.setObjectName(u"crosshair_tab")
        self.crosshair_tab.setEnabled(False)
        self.gridLayout_6 = QGridLayout(self.crosshair_tab)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.crosshair_hough_threshold_slider = QSlider(self.crosshair_tab)
        self.crosshair_hough_threshold_slider.setObjectName(u"crosshair_hough_threshold_slider")
        sizePolicy2.setHeightForWidth(self.crosshair_hough_threshold_slider.sizePolicy().hasHeightForWidth())
        self.crosshair_hough_threshold_slider.setSizePolicy(sizePolicy2)
        self.crosshair_hough_threshold_slider.setMinimumSize(QSize(255, 0))
        self.crosshair_hough_threshold_slider.setMaximum(255)
        self.crosshair_hough_threshold_slider.setOrientation(Qt.Orientation.Horizontal)
        self.crosshair_hough_threshold_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.crosshair_hough_threshold_slider.setTickInterval(0)

        self.gridLayout_6.addWidget(self.crosshair_hough_threshold_slider, 0, 2, 1, 1)

        self.crosshair_max_slope_spin = QDoubleSpinBox(self.crosshair_tab)
        self.crosshair_max_slope_spin.setObjectName(u"crosshair_max_slope_spin")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.crosshair_max_slope_spin.sizePolicy().hasHeightForWidth())
        self.crosshair_max_slope_spin.setSizePolicy(sizePolicy3)
        self.crosshair_max_slope_spin.setMinimumSize(QSize(100, 0))
        self.crosshair_max_slope_spin.setFont(font)
        self.crosshair_max_slope_spin.setMinimum(0.000000000000000)
        self.crosshair_max_slope_spin.setMaximum(180.000000000000000)

        self.gridLayout_6.addWidget(self.crosshair_max_slope_spin, 1, 3, 1, 1)

        self.crosshair_max_slope_slider = QSlider(self.crosshair_tab)
        self.crosshair_max_slope_slider.setObjectName(u"crosshair_max_slope_slider")
        sizePolicy2.setHeightForWidth(self.crosshair_max_slope_slider.sizePolicy().hasHeightForWidth())
        self.crosshair_max_slope_slider.setSizePolicy(sizePolicy2)
        self.crosshair_max_slope_slider.setMinimumSize(QSize(255, 0))
        self.crosshair_max_slope_slider.setMinimum(0)
        self.crosshair_max_slope_slider.setMaximum(180)
        self.crosshair_max_slope_slider.setOrientation(Qt.Orientation.Horizontal)
        self.crosshair_max_slope_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.crosshair_max_slope_slider.setTickInterval(0)

        self.gridLayout_6.addWidget(self.crosshair_max_slope_slider, 1, 2, 1, 1)

        self.crosshair_hough_threshold_spin = QSpinBox(self.crosshair_tab)
        self.crosshair_hough_threshold_spin.setObjectName(u"crosshair_hough_threshold_spin")
        sizePolicy3.setHeightForWidth(self.crosshair_hough_threshold_spin.sizePolicy().hasHeightForWidth())
        self.crosshair_hough_threshold_spin.setSizePolicy(sizePolicy3)
        self.crosshair_hough_threshold_spin.setMinimumSize(QSize(100, 0))
        self.crosshair_hough_threshold_spin.setFont(font)
        self.crosshair_hough_threshold_spin.setMaximum(255)

        self.gridLayout_6.addWidget(self.crosshair_hough_threshold_spin, 0, 3, 1, 1)

        self.crosshair_hough_threshold_label = QLabel(self.crosshair_tab)
        self.crosshair_hough_threshold_label.setObjectName(u"crosshair_hough_threshold_label")
        sizePolicy3.setHeightForWidth(self.crosshair_hough_threshold_label.sizePolicy().hasHeightForWidth())
        self.crosshair_hough_threshold_label.setSizePolicy(sizePolicy3)
        self.crosshair_hough_threshold_label.setMinimumSize(QSize(100, 0))
        self.crosshair_hough_threshold_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.crosshair_hough_threshold_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.crosshair_hough_threshold_label, 0, 0, 1, 2)

        self.crosshair_max_slope_label = QLabel(self.crosshair_tab)
        self.crosshair_max_slope_label.setObjectName(u"crosshair_max_slope_label")
        sizePolicy3.setHeightForWidth(self.crosshair_max_slope_label.sizePolicy().hasHeightForWidth())
        self.crosshair_max_slope_label.setSizePolicy(sizePolicy3)
        self.crosshair_max_slope_label.setMinimumSize(QSize(100, 0))
        self.crosshair_max_slope_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.crosshair_max_slope_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.crosshair_max_slope_label, 1, 0, 1, 2)

        self.crosshair_min_length_slider = QSlider(self.crosshair_tab)
        self.crosshair_min_length_slider.setObjectName(u"crosshair_min_length_slider")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.crosshair_min_length_slider.sizePolicy().hasHeightForWidth())
        self.crosshair_min_length_slider.setSizePolicy(sizePolicy4)
        self.crosshair_min_length_slider.setMinimumSize(QSize(255, 0))
        self.crosshair_min_length_slider.setMinimum(1)
        self.crosshair_min_length_slider.setMaximum(10000)
        self.crosshair_min_length_slider.setSingleStep(10)
        self.crosshair_min_length_slider.setValue(100)
        self.crosshair_min_length_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_6.addWidget(self.crosshair_min_length_slider, 2, 2, 1, 1)

        self.crosshair_min_length_spin = QSpinBox(self.crosshair_tab)
        self.crosshair_min_length_spin.setObjectName(u"crosshair_min_length_spin")
        sizePolicy3.setHeightForWidth(self.crosshair_min_length_spin.sizePolicy().hasHeightForWidth())
        self.crosshair_min_length_spin.setSizePolicy(sizePolicy3)
        self.crosshair_min_length_spin.setMinimumSize(QSize(100, 0))
        self.crosshair_min_length_spin.setFont(font)
        self.crosshair_min_length_spin.setMinimum(1)
        self.crosshair_min_length_spin.setMaximum(10000)
        self.crosshair_min_length_spin.setSingleStep(10)
        self.crosshair_min_length_spin.setValue(100)

        self.gridLayout_6.addWidget(self.crosshair_min_length_spin, 2, 3, 1, 1)

        self.crosshair_min_length_label = QLabel(self.crosshair_tab)
        self.crosshair_min_length_label.setObjectName(u"crosshair_min_length_label")
        sizePolicy3.setHeightForWidth(self.crosshair_min_length_label.sizePolicy().hasHeightForWidth())
        self.crosshair_min_length_label.setSizePolicy(sizePolicy3)
        self.crosshair_min_length_label.setMinimumSize(QSize(100, 0))
        self.crosshair_min_length_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.crosshair_min_length_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.crosshair_min_length_label, 2, 0, 1, 2)

        self.crosshair_distance_label = QLabel(self.crosshair_tab)
        self.crosshair_distance_label.setObjectName(u"crosshair_distance_label")
        sizePolicy3.setHeightForWidth(self.crosshair_distance_label.sizePolicy().hasHeightForWidth())
        self.crosshair_distance_label.setSizePolicy(sizePolicy3)
        self.crosshair_distance_label.setMinimumSize(QSize(100, 0))
        self.crosshair_distance_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.crosshair_distance_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.crosshair_distance_label, 3, 0, 1, 2)

        self.crosshair_distance_slider = QSlider(self.crosshair_tab)
        self.crosshair_distance_slider.setObjectName(u"crosshair_distance_slider")
        sizePolicy4.setHeightForWidth(self.crosshair_distance_slider.sizePolicy().hasHeightForWidth())
        self.crosshair_distance_slider.setSizePolicy(sizePolicy4)
        self.crosshair_distance_slider.setMinimumSize(QSize(250, 0))
        self.crosshair_distance_slider.setMinimum(1)
        self.crosshair_distance_slider.setMaximum(10000)
        self.crosshair_distance_slider.setSingleStep(10)
        self.crosshair_distance_slider.setValue(10)
        self.crosshair_distance_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_6.addWidget(self.crosshair_distance_slider, 3, 2, 1, 1)

        self.crosshair_distance_spin = QSpinBox(self.crosshair_tab)
        self.crosshair_distance_spin.setObjectName(u"crosshair_distance_spin")
        sizePolicy3.setHeightForWidth(self.crosshair_distance_spin.sizePolicy().hasHeightForWidth())
        self.crosshair_distance_spin.setSizePolicy(sizePolicy3)
        self.crosshair_distance_spin.setMinimumSize(QSize(100, 0))
        self.crosshair_distance_spin.setFont(font)
        self.crosshair_distance_spin.setMinimum(1)
        self.crosshair_distance_spin.setMaximum(10000)
        self.crosshair_distance_spin.setSingleStep(10)
        self.crosshair_distance_spin.setValue(10)

        self.gridLayout_6.addWidget(self.crosshair_distance_spin, 3, 3, 1, 1)

        self.fitting_tabs.addTab(self.crosshair_tab, "")
        self.elliptical_tab = QWidget()
        self.elliptical_tab.setObjectName(u"elliptical_tab")
        self.elliptical_tab.setEnabled(False)
        self.gridLayout_5 = QGridLayout(self.elliptical_tab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.circularity_label = QLabel(self.elliptical_tab)
        self.circularity_label.setObjectName(u"circularity_label")
        sizePolicy3.setHeightForWidth(self.circularity_label.sizePolicy().hasHeightForWidth())
        self.circularity_label.setSizePolicy(sizePolicy3)
        self.circularity_label.setMinimumSize(QSize(100, 0))
        self.circularity_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.circularity_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.circularity_label, 0, 0, 1, 1)

        self.circularity_slider = QSlider(self.elliptical_tab)
        self.circularity_slider.setObjectName(u"circularity_slider")
        sizePolicy4.setHeightForWidth(self.circularity_slider.sizePolicy().hasHeightForWidth())
        self.circularity_slider.setSizePolicy(sizePolicy4)
        self.circularity_slider.setMinimumSize(QSize(250, 0))
        self.circularity_slider.setMinimum(10)
        self.circularity_slider.setMaximum(100)
        self.circularity_slider.setSingleStep(1)
        self.circularity_slider.setValue(50)
        self.circularity_slider.setOrientation(Qt.Orientation.Horizontal)
        self.circularity_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.circularity_slider.setTickInterval(0)

        self.gridLayout_5.addWidget(self.circularity_slider, 0, 1, 1, 1)

        self.circularity_spin = QDoubleSpinBox(self.elliptical_tab)
        self.circularity_spin.setObjectName(u"circularity_spin")
        sizePolicy3.setHeightForWidth(self.circularity_spin.sizePolicy().hasHeightForWidth())
        self.circularity_spin.setSizePolicy(sizePolicy3)
        self.circularity_spin.setMinimumSize(QSize(100, 0))
        self.circularity_spin.setFont(font)
        self.circularity_spin.setMinimum(0.100000000000000)
        self.circularity_spin.setMaximum(1.000000000000000)
        self.circularity_spin.setSingleStep(0.100000000000000)
        self.circularity_spin.setValue(0.500000000000000)

        self.gridLayout_5.addWidget(self.circularity_spin, 0, 2, 1, 1)

        self.elliptical_min_size_label = QLabel(self.elliptical_tab)
        self.elliptical_min_size_label.setObjectName(u"elliptical_min_size_label")
        sizePolicy3.setHeightForWidth(self.elliptical_min_size_label.sizePolicy().hasHeightForWidth())
        self.elliptical_min_size_label.setSizePolicy(sizePolicy3)
        self.elliptical_min_size_label.setMinimumSize(QSize(100, 0))
        self.elliptical_min_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.elliptical_min_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.elliptical_min_size_label, 1, 0, 1, 1)

        self.elliptical_min_size_slider = QSlider(self.elliptical_tab)
        self.elliptical_min_size_slider.setObjectName(u"elliptical_min_size_slider")
        sizePolicy4.setHeightForWidth(self.elliptical_min_size_slider.sizePolicy().hasHeightForWidth())
        self.elliptical_min_size_slider.setSizePolicy(sizePolicy4)
        self.elliptical_min_size_slider.setMinimumSize(QSize(250, 0))
        self.elliptical_min_size_slider.setMaximum(100000)
        self.elliptical_min_size_slider.setSingleStep(100)
        self.elliptical_min_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_5.addWidget(self.elliptical_min_size_slider, 1, 1, 1, 1)

        self.elliptical_min_size_spin = QSpinBox(self.elliptical_tab)
        self.elliptical_min_size_spin.setObjectName(u"elliptical_min_size_spin")
        sizePolicy3.setHeightForWidth(self.elliptical_min_size_spin.sizePolicy().hasHeightForWidth())
        self.elliptical_min_size_spin.setSizePolicy(sizePolicy3)
        self.elliptical_min_size_spin.setMinimumSize(QSize(100, 0))
        self.elliptical_min_size_spin.setFont(font)
        self.elliptical_min_size_spin.setMaximum(100000)
        self.elliptical_min_size_spin.setSingleStep(100)

        self.gridLayout_5.addWidget(self.elliptical_min_size_spin, 1, 2, 1, 1)

        self.elliptical_max_size_label = QLabel(self.elliptical_tab)
        self.elliptical_max_size_label.setObjectName(u"elliptical_max_size_label")
        sizePolicy3.setHeightForWidth(self.elliptical_max_size_label.sizePolicy().hasHeightForWidth())
        self.elliptical_max_size_label.setSizePolicy(sizePolicy3)
        self.elliptical_max_size_label.setMinimumSize(QSize(100, 0))
        self.elliptical_max_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.elliptical_max_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.elliptical_max_size_label, 2, 0, 1, 1)

        self.elliptical_max_size_slider = QSlider(self.elliptical_tab)
        self.elliptical_max_size_slider.setObjectName(u"elliptical_max_size_slider")
        sizePolicy4.setHeightForWidth(self.elliptical_max_size_slider.sizePolicy().hasHeightForWidth())
        self.elliptical_max_size_slider.setSizePolicy(sizePolicy4)
        self.elliptical_max_size_slider.setMinimumSize(QSize(250, 0))
        self.elliptical_max_size_slider.setMaximum(100000)
        self.elliptical_max_size_slider.setSingleStep(100)
        self.elliptical_max_size_slider.setValue(100000)
        self.elliptical_max_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_5.addWidget(self.elliptical_max_size_slider, 2, 1, 1, 1)

        self.elliptical_max_size_spin = QSpinBox(self.elliptical_tab)
        self.elliptical_max_size_spin.setObjectName(u"elliptical_max_size_spin")
        sizePolicy3.setHeightForWidth(self.elliptical_max_size_spin.sizePolicy().hasHeightForWidth())
        self.elliptical_max_size_spin.setSizePolicy(sizePolicy3)
        self.elliptical_max_size_spin.setMinimumSize(QSize(100, 0))
        self.elliptical_max_size_spin.setFont(font)
        self.elliptical_max_size_spin.setMaximum(100000)
        self.elliptical_max_size_spin.setSingleStep(100)
        self.elliptical_max_size_spin.setValue(100000)

        self.gridLayout_5.addWidget(self.elliptical_max_size_spin, 2, 2, 1, 1)

        self.fitting_tabs.addTab(self.elliptical_tab, "")
        self.rect_tab = QWidget()
        self.rect_tab.setObjectName(u"rect_tab")
        self.rect_tab.setEnabled(False)
        self.gridLayout_7 = QGridLayout(self.rect_tab)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.rect_min_size_label = QLabel(self.rect_tab)
        self.rect_min_size_label.setObjectName(u"rect_min_size_label")
        sizePolicy3.setHeightForWidth(self.rect_min_size_label.sizePolicy().hasHeightForWidth())
        self.rect_min_size_label.setSizePolicy(sizePolicy3)
        self.rect_min_size_label.setMinimumSize(QSize(100, 0))
        self.rect_min_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.rect_min_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.rect_min_size_label, 0, 0, 1, 1)

        self.rect_min_size_spin = QSpinBox(self.rect_tab)
        self.rect_min_size_spin.setObjectName(u"rect_min_size_spin")
        sizePolicy3.setHeightForWidth(self.rect_min_size_spin.sizePolicy().hasHeightForWidth())
        self.rect_min_size_spin.setSizePolicy(sizePolicy3)
        self.rect_min_size_spin.setMinimumSize(QSize(100, 0))
        self.rect_min_size_spin.setMaximum(100000)
        self.rect_min_size_spin.setSingleStep(100)

        self.gridLayout_7.addWidget(self.rect_min_size_spin, 0, 2, 1, 1)

        self.rect_min_size_slider = QSlider(self.rect_tab)
        self.rect_min_size_slider.setObjectName(u"rect_min_size_slider")
        sizePolicy4.setHeightForWidth(self.rect_min_size_slider.sizePolicy().hasHeightForWidth())
        self.rect_min_size_slider.setSizePolicy(sizePolicy4)
        self.rect_min_size_slider.setMinimumSize(QSize(255, 0))
        self.rect_min_size_slider.setMaximum(100000)
        self.rect_min_size_slider.setSingleStep(100)
        self.rect_min_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_7.addWidget(self.rect_min_size_slider, 0, 1, 1, 1)

        self.rect_max_size_label = QLabel(self.rect_tab)
        self.rect_max_size_label.setObjectName(u"rect_max_size_label")
        sizePolicy3.setHeightForWidth(self.rect_max_size_label.sizePolicy().hasHeightForWidth())
        self.rect_max_size_label.setSizePolicy(sizePolicy3)
        self.rect_max_size_label.setMinimumSize(QSize(100, 0))
        self.rect_max_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.rect_max_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.rect_max_size_label, 1, 0, 1, 1)

        self.rect_max_size_slider = QSlider(self.rect_tab)
        self.rect_max_size_slider.setObjectName(u"rect_max_size_slider")
        sizePolicy4.setHeightForWidth(self.rect_max_size_slider.sizePolicy().hasHeightForWidth())
        self.rect_max_size_slider.setSizePolicy(sizePolicy4)
        self.rect_max_size_slider.setMinimumSize(QSize(250, 0))
        self.rect_max_size_slider.setMaximum(100000)
        self.rect_max_size_slider.setSingleStep(100)
        self.rect_max_size_slider.setValue(100000)
        self.rect_max_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_7.addWidget(self.rect_max_size_slider, 1, 1, 1, 1)

        self.rect_max_size_spin = QSpinBox(self.rect_tab)
        self.rect_max_size_spin.setObjectName(u"rect_max_size_spin")
        sizePolicy3.setHeightForWidth(self.rect_max_size_spin.sizePolicy().hasHeightForWidth())
        self.rect_max_size_spin.setSizePolicy(sizePolicy3)
        self.rect_max_size_spin.setMinimumSize(QSize(100, 0))
        self.rect_max_size_spin.setMaximum(100000)
        self.rect_max_size_spin.setSingleStep(100)
        self.rect_max_size_spin.setValue(100000)

        self.gridLayout_7.addWidget(self.rect_max_size_spin, 1, 2, 1, 1)

        self.fitting_tabs.addTab(self.rect_tab, "")
        self.arch_tab = QWidget()
        self.arch_tab.setObjectName(u"arch_tab")
        self.gridLayout_10 = QGridLayout(self.arch_tab)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.arch_u_score_label = QLabel(self.arch_tab)
        self.arch_u_score_label.setObjectName(u"arch_u_score_label")
        sizePolicy3.setHeightForWidth(self.arch_u_score_label.sizePolicy().hasHeightForWidth())
        self.arch_u_score_label.setSizePolicy(sizePolicy3)
        self.arch_u_score_label.setMinimumSize(QSize(100, 0))
        self.arch_u_score_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.arch_u_score_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_10.addWidget(self.arch_u_score_label, 0, 0, 1, 1)

        self.arch_u_score_slider = QSlider(self.arch_tab)
        self.arch_u_score_slider.setObjectName(u"arch_u_score_slider")
        sizePolicy4.setHeightForWidth(self.arch_u_score_slider.sizePolicy().hasHeightForWidth())
        self.arch_u_score_slider.setSizePolicy(sizePolicy4)
        self.arch_u_score_slider.setMinimumSize(QSize(250, 0))
        self.arch_u_score_slider.setMinimum(10)
        self.arch_u_score_slider.setMaximum(100)
        self.arch_u_score_slider.setSingleStep(1)
        self.arch_u_score_slider.setValue(50)
        self.arch_u_score_slider.setOrientation(Qt.Orientation.Horizontal)
        self.arch_u_score_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.arch_u_score_slider.setTickInterval(0)

        self.gridLayout_10.addWidget(self.arch_u_score_slider, 0, 1, 1, 1)

        self.arch_u_score_spin = QDoubleSpinBox(self.arch_tab)
        self.arch_u_score_spin.setObjectName(u"arch_u_score_spin")
        sizePolicy3.setHeightForWidth(self.arch_u_score_spin.sizePolicy().hasHeightForWidth())
        self.arch_u_score_spin.setSizePolicy(sizePolicy3)
        self.arch_u_score_spin.setMinimumSize(QSize(100, 0))
        self.arch_u_score_spin.setMinimum(0.100000000000000)
        self.arch_u_score_spin.setMaximum(1.000000000000000)
        self.arch_u_score_spin.setSingleStep(0.100000000000000)
        self.arch_u_score_spin.setValue(0.500000000000000)

        self.gridLayout_10.addWidget(self.arch_u_score_spin, 0, 2, 1, 1)

        self.arch_min_size_label = QLabel(self.arch_tab)
        self.arch_min_size_label.setObjectName(u"arch_min_size_label")
        sizePolicy3.setHeightForWidth(self.arch_min_size_label.sizePolicy().hasHeightForWidth())
        self.arch_min_size_label.setSizePolicy(sizePolicy3)
        self.arch_min_size_label.setMinimumSize(QSize(100, 0))
        self.arch_min_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.arch_min_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_10.addWidget(self.arch_min_size_label, 1, 0, 1, 1)

        self.arch_min_size_slider = QSlider(self.arch_tab)
        self.arch_min_size_slider.setObjectName(u"arch_min_size_slider")
        sizePolicy4.setHeightForWidth(self.arch_min_size_slider.sizePolicy().hasHeightForWidth())
        self.arch_min_size_slider.setSizePolicy(sizePolicy4)
        self.arch_min_size_slider.setMinimumSize(QSize(250, 0))
        self.arch_min_size_slider.setMaximum(100000)
        self.arch_min_size_slider.setSingleStep(100)
        self.arch_min_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_10.addWidget(self.arch_min_size_slider, 1, 1, 1, 1)

        self.arch_min_size_spin = QSpinBox(self.arch_tab)
        self.arch_min_size_spin.setObjectName(u"arch_min_size_spin")
        sizePolicy3.setHeightForWidth(self.arch_min_size_spin.sizePolicy().hasHeightForWidth())
        self.arch_min_size_spin.setSizePolicy(sizePolicy3)
        self.arch_min_size_spin.setMinimumSize(QSize(100, 0))
        self.arch_min_size_spin.setMaximum(100000)
        self.arch_min_size_spin.setSingleStep(100)

        self.gridLayout_10.addWidget(self.arch_min_size_spin, 1, 2, 1, 1)

        self.arch_max_size_label = QLabel(self.arch_tab)
        self.arch_max_size_label.setObjectName(u"arch_max_size_label")
        sizePolicy3.setHeightForWidth(self.arch_max_size_label.sizePolicy().hasHeightForWidth())
        self.arch_max_size_label.setSizePolicy(sizePolicy3)
        self.arch_max_size_label.setMinimumSize(QSize(100, 0))
        self.arch_max_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.arch_max_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_10.addWidget(self.arch_max_size_label, 2, 0, 1, 1)

        self.arch_max_size_slider = QSlider(self.arch_tab)
        self.arch_max_size_slider.setObjectName(u"arch_max_size_slider")
        sizePolicy4.setHeightForWidth(self.arch_max_size_slider.sizePolicy().hasHeightForWidth())
        self.arch_max_size_slider.setSizePolicy(sizePolicy4)
        self.arch_max_size_slider.setMinimumSize(QSize(250, 0))
        self.arch_max_size_slider.setMaximum(100000)
        self.arch_max_size_slider.setSingleStep(100)
        self.arch_max_size_slider.setValue(100000)
        self.arch_max_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_10.addWidget(self.arch_max_size_slider, 2, 1, 1, 1)

        self.arch_max_size_spin = QSpinBox(self.arch_tab)
        self.arch_max_size_spin.setObjectName(u"arch_max_size_spin")
        sizePolicy3.setHeightForWidth(self.arch_max_size_spin.sizePolicy().hasHeightForWidth())
        self.arch_max_size_spin.setSizePolicy(sizePolicy3)
        self.arch_max_size_spin.setMinimumSize(QSize(100, 0))
        self.arch_max_size_spin.setMaximum(100000)
        self.arch_max_size_spin.setSingleStep(100)
        self.arch_max_size_spin.setValue(100000)

        self.gridLayout_10.addWidget(self.arch_max_size_spin, 2, 2, 1, 1)

        self.fitting_tabs.addTab(self.arch_tab, "")

        self.gridLayout.addWidget(self.fitting_tabs, 6, 0, 1, 2)

        self.feature_fitting_header = QLabel(self.feature_fitting_frame)
        self.feature_fitting_header.setObjectName(u"feature_fitting_header")
        sizePolicy1.setHeightForWidth(self.feature_fitting_header.sizePolicy().hasHeightForWidth())
        self.feature_fitting_header.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.feature_fitting_header.setFont(font1)

        self.gridLayout.addWidget(self.feature_fitting_header, 0, 0, 1, 2)

        self.rect_fit_check = QCheckBox(self.feature_fitting_frame)
        self.rect_fit_check.setObjectName(u"rect_fit_check")
        self.rect_fit_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout.addWidget(self.rect_fit_check, 1, 1, 1, 1)

        self.arch_fit_check = QCheckBox(self.feature_fitting_frame)
        self.arch_fit_check.setObjectName(u"arch_fit_check")
        self.arch_fit_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout.addWidget(self.arch_fit_check, 2, 1, 1, 1)

        self.elliptical_fit_check = QCheckBox(self.feature_fitting_frame)
        self.elliptical_fit_check.setObjectName(u"elliptical_fit_check")
        self.elliptical_fit_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout.addWidget(self.elliptical_fit_check, 2, 0, 1, 1)

        self.crosshair_fit_check = QCheckBox(self.feature_fitting_frame)
        self.crosshair_fit_check.setObjectName(u"crosshair_fit_check")
        self.crosshair_fit_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout.addWidget(self.crosshair_fit_check, 1, 0, 1, 1)


        self.gridLayout_2.addWidget(self.feature_fitting_frame, 2, 3, 1, 1)

        self.stream_window = QGraphicsView(featureFinder)
        self.stream_window.setObjectName(u"stream_window")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.stream_window.sizePolicy().hasHeightForWidth())
        self.stream_window.setSizePolicy(sizePolicy5)
        self.stream_window.setMinimumSize(QSize(700, 700))
        self.stream_window.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.CrossCursor))
        self.stream_window.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.stream_window.setAutoFillBackground(False)
        self.stream_window.setDragMode(QGraphicsView.DragMode.ScrollHandDrag)

        self.gridLayout_2.addWidget(self.stream_window, 0, 0, 4, 2)

        self.empty_frame = QFrame(featureFinder)
        self.empty_frame.setObjectName(u"empty_frame")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.empty_frame.sizePolicy().hasHeightForWidth())
        self.empty_frame.setSizePolicy(sizePolicy6)
        self.empty_frame.setMaximumSize(QSize(1000, 16777215))
        self.empty_frame.setFrameShape(QFrame.Shape.NoFrame)
        self.empty_frame.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout_2.addWidget(self.empty_frame, 3, 3, 1, 1)

        self.edge_detection_frame = QFrame(featureFinder)
        self.edge_detection_frame.setObjectName(u"edge_detection_frame")
        self.edge_detection_frame.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.edge_detection_frame.sizePolicy().hasHeightForWidth())
        self.edge_detection_frame.setSizePolicy(sizePolicy1)
        self.edge_detection_frame.setMinimumSize(QSize(0, 0))
        self.edge_detection_frame.setMaximumSize(QSize(1000, 16777215))
        self.edge_detection_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.edge_detection_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_3 = QGridLayout(self.edge_detection_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.canny_edge_check = QCheckBox(self.edge_detection_frame)
        self.canny_edge_check.setObjectName(u"canny_edge_check")
        self.canny_edge_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout_3.addWidget(self.canny_edge_check, 1, 2, 1, 2)

        self.edge_detection_header = QLabel(self.edge_detection_frame)
        self.edge_detection_header.setObjectName(u"edge_detection_header")
        sizePolicy1.setHeightForWidth(self.edge_detection_header.sizePolicy().hasHeightForWidth())
        self.edge_detection_header.setSizePolicy(sizePolicy1)
        self.edge_detection_header.setFont(font1)
        self.edge_detection_header.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_3.addWidget(self.edge_detection_header, 0, 0, 1, 4)

        self.show_processed_image_check = QCheckBox(self.edge_detection_frame)
        self.show_processed_image_check.setObjectName(u"show_processed_image_check")
        self.show_processed_image_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout_3.addWidget(self.show_processed_image_check, 2, 0, 1, 1)

        self.invert_image_check = QCheckBox(self.edge_detection_frame)
        self.invert_image_check.setObjectName(u"invert_image_check")
        self.invert_image_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout_3.addWidget(self.invert_image_check, 1, 0, 1, 2)

        self.reduce_noise_check = QCheckBox(self.edge_detection_frame)
        self.reduce_noise_check.setObjectName(u"reduce_noise_check")
        self.reduce_noise_check.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout_3.addWidget(self.reduce_noise_check, 2, 2, 1, 1)

        self.edge_detection_tabs = QTabWidget(self.edge_detection_frame)
        self.edge_detection_tabs.setObjectName(u"edge_detection_tabs")
        self.edge_detection_tabs.setEnabled(False)
        self.edge_detection_tabs.setMinimumSize(QSize(0, 100))
        self.classic_tab = QWidget()
        self.classic_tab.setObjectName(u"classic_tab")
        self.gridLayout_12 = QGridLayout(self.classic_tab)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.gauss_blur_label = QLabel(self.classic_tab)
        self.gauss_blur_label.setObjectName(u"gauss_blur_label")
        sizePolicy3.setHeightForWidth(self.gauss_blur_label.sizePolicy().hasHeightForWidth())
        self.gauss_blur_label.setSizePolicy(sizePolicy3)
        self.gauss_blur_label.setMinimumSize(QSize(100, 0))
        self.gauss_blur_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.gauss_blur_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_12.addWidget(self.gauss_blur_label, 1, 0, 1, 1)

        self.feature_max_size_slider = QSlider(self.classic_tab)
        self.feature_max_size_slider.setObjectName(u"feature_max_size_slider")
        sizePolicy4.setHeightForWidth(self.feature_max_size_slider.sizePolicy().hasHeightForWidth())
        self.feature_max_size_slider.setSizePolicy(sizePolicy4)
        self.feature_max_size_slider.setMinimumSize(QSize(250, 0))
        self.feature_max_size_slider.setMaximum(100000)
        self.feature_max_size_slider.setSingleStep(100)
        self.feature_max_size_slider.setValue(100000)
        self.feature_max_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_12.addWidget(self.feature_max_size_slider, 3, 1, 1, 1)

        self.feature_max_size_spin = QSpinBox(self.classic_tab)
        self.feature_max_size_spin.setObjectName(u"feature_max_size_spin")
        sizePolicy3.setHeightForWidth(self.feature_max_size_spin.sizePolicy().hasHeightForWidth())
        self.feature_max_size_spin.setSizePolicy(sizePolicy3)
        self.feature_max_size_spin.setMinimumSize(QSize(100, 0))
        self.feature_max_size_spin.setFont(font)
        self.feature_max_size_spin.setMaximum(100000)
        self.feature_max_size_spin.setSingleStep(100)
        self.feature_max_size_spin.setValue(100000)

        self.gridLayout_12.addWidget(self.feature_max_size_spin, 3, 2, 1, 1)

        self.gauss_blur_slider = QSlider(self.classic_tab)
        self.gauss_blur_slider.setObjectName(u"gauss_blur_slider")
        sizePolicy4.setHeightForWidth(self.gauss_blur_slider.sizePolicy().hasHeightForWidth())
        self.gauss_blur_slider.setSizePolicy(sizePolicy4)
        self.gauss_blur_slider.setMinimumSize(QSize(255, 0))
        self.gauss_blur_slider.setMinimum(1)
        self.gauss_blur_slider.setMaximum(200)
        self.gauss_blur_slider.setSingleStep(1)
        self.gauss_blur_slider.setValue(1)
        self.gauss_blur_slider.setOrientation(Qt.Orientation.Horizontal)
        self.gauss_blur_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.gauss_blur_slider.setTickInterval(0)

        self.gridLayout_12.addWidget(self.gauss_blur_slider, 1, 1, 1, 1)

        self.feature_min_size_spin = QSpinBox(self.classic_tab)
        self.feature_min_size_spin.setObjectName(u"feature_min_size_spin")
        sizePolicy3.setHeightForWidth(self.feature_min_size_spin.sizePolicy().hasHeightForWidth())
        self.feature_min_size_spin.setSizePolicy(sizePolicy3)
        self.feature_min_size_spin.setMinimumSize(QSize(100, 0))
        self.feature_min_size_spin.setFont(font)
        self.feature_min_size_spin.setMaximum(100000)
        self.feature_min_size_spin.setSingleStep(100)
        self.feature_min_size_spin.setValue(100)

        self.gridLayout_12.addWidget(self.feature_min_size_spin, 2, 2, 1, 1)

        self.pixel_threshold_label = QLabel(self.classic_tab)
        self.pixel_threshold_label.setObjectName(u"pixel_threshold_label")
        sizePolicy3.setHeightForWidth(self.pixel_threshold_label.sizePolicy().hasHeightForWidth())
        self.pixel_threshold_label.setSizePolicy(sizePolicy3)
        self.pixel_threshold_label.setMinimumSize(QSize(100, 0))
        self.pixel_threshold_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.pixel_threshold_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_12.addWidget(self.pixel_threshold_label, 0, 0, 1, 1)

        self.pixel_threshold_spin = QSpinBox(self.classic_tab)
        self.pixel_threshold_spin.setObjectName(u"pixel_threshold_spin")
        sizePolicy1.setHeightForWidth(self.pixel_threshold_spin.sizePolicy().hasHeightForWidth())
        self.pixel_threshold_spin.setSizePolicy(sizePolicy1)
        self.pixel_threshold_spin.setMinimumSize(QSize(100, 0))
        self.pixel_threshold_spin.setFont(font)
        self.pixel_threshold_spin.setMaximum(255)
        self.pixel_threshold_spin.setSingleStep(1)

        self.gridLayout_12.addWidget(self.pixel_threshold_spin, 0, 2, 1, 1)

        self.feature_min_size_label = QLabel(self.classic_tab)
        self.feature_min_size_label.setObjectName(u"feature_min_size_label")
        sizePolicy3.setHeightForWidth(self.feature_min_size_label.sizePolicy().hasHeightForWidth())
        self.feature_min_size_label.setSizePolicy(sizePolicy3)
        self.feature_min_size_label.setMinimumSize(QSize(100, 0))
        self.feature_min_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.feature_min_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_12.addWidget(self.feature_min_size_label, 2, 0, 1, 1)

        self.gauss_blur_spin = QSpinBox(self.classic_tab)
        self.gauss_blur_spin.setObjectName(u"gauss_blur_spin")
        sizePolicy3.setHeightForWidth(self.gauss_blur_spin.sizePolicy().hasHeightForWidth())
        self.gauss_blur_spin.setSizePolicy(sizePolicy3)
        self.gauss_blur_spin.setMinimumSize(QSize(100, 0))
        self.gauss_blur_spin.setFont(font)
        self.gauss_blur_spin.setMinimum(1)
        self.gauss_blur_spin.setMaximum(200)
        self.gauss_blur_spin.setSingleStep(1)

        self.gridLayout_12.addWidget(self.gauss_blur_spin, 1, 2, 1, 1)

        self.feature_max_size_label = QLabel(self.classic_tab)
        self.feature_max_size_label.setObjectName(u"feature_max_size_label")
        sizePolicy3.setHeightForWidth(self.feature_max_size_label.sizePolicy().hasHeightForWidth())
        self.feature_max_size_label.setSizePolicy(sizePolicy3)
        self.feature_max_size_label.setMinimumSize(QSize(100, 0))
        self.feature_max_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.feature_max_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_12.addWidget(self.feature_max_size_label, 3, 0, 1, 1)

        self.pixel_threshold_slider = QSlider(self.classic_tab)
        self.pixel_threshold_slider.setObjectName(u"pixel_threshold_slider")
        sizePolicy4.setHeightForWidth(self.pixel_threshold_slider.sizePolicy().hasHeightForWidth())
        self.pixel_threshold_slider.setSizePolicy(sizePolicy4)
        self.pixel_threshold_slider.setMinimumSize(QSize(255, 0))
        self.pixel_threshold_slider.setMaximum(255)
        self.pixel_threshold_slider.setSingleStep(1)
        self.pixel_threshold_slider.setOrientation(Qt.Orientation.Horizontal)
        self.pixel_threshold_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.pixel_threshold_slider.setTickInterval(0)

        self.gridLayout_12.addWidget(self.pixel_threshold_slider, 0, 1, 1, 1)

        self.feature_min_size_slider = QSlider(self.classic_tab)
        self.feature_min_size_slider.setObjectName(u"feature_min_size_slider")
        sizePolicy4.setHeightForWidth(self.feature_min_size_slider.sizePolicy().hasHeightForWidth())
        self.feature_min_size_slider.setSizePolicy(sizePolicy4)
        self.feature_min_size_slider.setMinimumSize(QSize(255, 0))
        self.feature_min_size_slider.setMaximum(100000)
        self.feature_min_size_slider.setSingleStep(100)
        self.feature_min_size_slider.setValue(100)
        self.feature_min_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_12.addWidget(self.feature_min_size_slider, 2, 1, 1, 1)

        self.edge_detection_tabs.addTab(self.classic_tab, "")
        self.canny_tab = QWidget()
        self.canny_tab.setObjectName(u"canny_tab")
        self.gridLayout_13 = QGridLayout(self.canny_tab)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.canny_min_label = QLabel(self.canny_tab)
        self.canny_min_label.setObjectName(u"canny_min_label")
        sizePolicy3.setHeightForWidth(self.canny_min_label.sizePolicy().hasHeightForWidth())
        self.canny_min_label.setSizePolicy(sizePolicy3)
        self.canny_min_label.setMinimumSize(QSize(100, 0))
        self.canny_min_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.canny_min_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_13.addWidget(self.canny_min_label, 0, 0, 1, 1)

        self.canny_min_slider = QSlider(self.canny_tab)
        self.canny_min_slider.setObjectName(u"canny_min_slider")
        sizePolicy4.setHeightForWidth(self.canny_min_slider.sizePolicy().hasHeightForWidth())
        self.canny_min_slider.setSizePolicy(sizePolicy4)
        self.canny_min_slider.setMinimumSize(QSize(255, 0))
        self.canny_min_slider.setMaximum(100000)
        self.canny_min_slider.setSingleStep(100)
        self.canny_min_slider.setValue(100)
        self.canny_min_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_13.addWidget(self.canny_min_slider, 0, 1, 1, 1)

        self.canny_min_spin = QSpinBox(self.canny_tab)
        self.canny_min_spin.setObjectName(u"canny_min_spin")
        sizePolicy3.setHeightForWidth(self.canny_min_spin.sizePolicy().hasHeightForWidth())
        self.canny_min_spin.setSizePolicy(sizePolicy3)
        self.canny_min_spin.setMinimumSize(QSize(100, 0))
        self.canny_min_spin.setFont(font)
        self.canny_min_spin.setMaximum(100000)
        self.canny_min_spin.setSingleStep(100)
        self.canny_min_spin.setValue(100)

        self.gridLayout_13.addWidget(self.canny_min_spin, 0, 2, 1, 1)

        self.canny_max_label = QLabel(self.canny_tab)
        self.canny_max_label.setObjectName(u"canny_max_label")
        sizePolicy3.setHeightForWidth(self.canny_max_label.sizePolicy().hasHeightForWidth())
        self.canny_max_label.setSizePolicy(sizePolicy3)
        self.canny_max_label.setMinimumSize(QSize(100, 0))
        self.canny_max_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.canny_max_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_13.addWidget(self.canny_max_label, 1, 0, 1, 1)

        self.canny_max_slider = QSlider(self.canny_tab)
        self.canny_max_slider.setObjectName(u"canny_max_slider")
        sizePolicy4.setHeightForWidth(self.canny_max_slider.sizePolicy().hasHeightForWidth())
        self.canny_max_slider.setSizePolicy(sizePolicy4)
        self.canny_max_slider.setMinimumSize(QSize(250, 0))
        self.canny_max_slider.setMaximum(100000)
        self.canny_max_slider.setSingleStep(100)
        self.canny_max_slider.setValue(100000)
        self.canny_max_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_13.addWidget(self.canny_max_slider, 1, 1, 1, 1)

        self.canny_max_spin = QSpinBox(self.canny_tab)
        self.canny_max_spin.setObjectName(u"canny_max_spin")
        sizePolicy3.setHeightForWidth(self.canny_max_spin.sizePolicy().hasHeightForWidth())
        self.canny_max_spin.setSizePolicy(sizePolicy3)
        self.canny_max_spin.setMinimumSize(QSize(100, 0))
        self.canny_max_spin.setFont(font)
        self.canny_max_spin.setMaximum(100000)
        self.canny_max_spin.setSingleStep(100)
        self.canny_max_spin.setValue(100000)

        self.gridLayout_13.addWidget(self.canny_max_spin, 1, 2, 1, 1)

        self.edge_detection_tabs.addTab(self.canny_tab, "")
        self.noise_normalize_tab = QWidget()
        self.noise_normalize_tab.setObjectName(u"noise_normalize_tab")
        self.gridLayout_14 = QGridLayout(self.noise_normalize_tab)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.winsor_percentile_label = QLabel(self.noise_normalize_tab)
        self.winsor_percentile_label.setObjectName(u"winsor_percentile_label")
        sizePolicy3.setHeightForWidth(self.winsor_percentile_label.sizePolicy().hasHeightForWidth())
        self.winsor_percentile_label.setSizePolicy(sizePolicy3)
        self.winsor_percentile_label.setMinimumSize(QSize(100, 0))
        self.winsor_percentile_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.winsor_percentile_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_14.addWidget(self.winsor_percentile_label, 0, 0, 1, 1)

        self.winsor_percentile_slider = QSlider(self.noise_normalize_tab)
        self.winsor_percentile_slider.setObjectName(u"winsor_percentile_slider")
        sizePolicy2.setHeightForWidth(self.winsor_percentile_slider.sizePolicy().hasHeightForWidth())
        self.winsor_percentile_slider.setSizePolicy(sizePolicy2)
        self.winsor_percentile_slider.setMinimumSize(QSize(255, 0))
        self.winsor_percentile_slider.setMinimum(1)
        self.winsor_percentile_slider.setValue(85)
        self.winsor_percentile_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_14.addWidget(self.winsor_percentile_slider, 0, 1, 1, 1)

        self.winsor_percentile_spin = QSpinBox(self.noise_normalize_tab)
        self.winsor_percentile_spin.setObjectName(u"winsor_percentile_spin")
        sizePolicy3.setHeightForWidth(self.winsor_percentile_spin.sizePolicy().hasHeightForWidth())
        self.winsor_percentile_spin.setSizePolicy(sizePolicy3)
        self.winsor_percentile_spin.setMinimumSize(QSize(100, 0))
        self.winsor_percentile_spin.setFont(font)
        self.winsor_percentile_spin.setMinimum(1)
        self.winsor_percentile_spin.setValue(85)

        self.gridLayout_14.addWidget(self.winsor_percentile_spin, 0, 2, 1, 1)

        self.noise_percentile_min_label = QLabel(self.noise_normalize_tab)
        self.noise_percentile_min_label.setObjectName(u"noise_percentile_min_label")
        sizePolicy3.setHeightForWidth(self.noise_percentile_min_label.sizePolicy().hasHeightForWidth())
        self.noise_percentile_min_label.setSizePolicy(sizePolicy3)
        self.noise_percentile_min_label.setMinimumSize(QSize(100, 0))
        self.noise_percentile_min_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.noise_percentile_min_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_14.addWidget(self.noise_percentile_min_label, 1, 0, 1, 1)

        self.noise_percentile_min_slider = QSlider(self.noise_normalize_tab)
        self.noise_percentile_min_slider.setObjectName(u"noise_percentile_min_slider")
        sizePolicy2.setHeightForWidth(self.noise_percentile_min_slider.sizePolicy().hasHeightForWidth())
        self.noise_percentile_min_slider.setSizePolicy(sizePolicy2)
        self.noise_percentile_min_slider.setMinimumSize(QSize(255, 0))
        self.noise_percentile_min_slider.setMinimum(1)
        self.noise_percentile_min_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_14.addWidget(self.noise_percentile_min_slider, 1, 1, 1, 1)

        self.noise_percentile_min_spin = QSpinBox(self.noise_normalize_tab)
        self.noise_percentile_min_spin.setObjectName(u"noise_percentile_min_spin")
        sizePolicy3.setHeightForWidth(self.noise_percentile_min_spin.sizePolicy().hasHeightForWidth())
        self.noise_percentile_min_spin.setSizePolicy(sizePolicy3)
        self.noise_percentile_min_spin.setMinimumSize(QSize(100, 0))
        self.noise_percentile_min_spin.setFont(font)
        self.noise_percentile_min_spin.setMinimum(1)

        self.gridLayout_14.addWidget(self.noise_percentile_min_spin, 1, 2, 1, 1)

        self.noise_percentile_max_label = QLabel(self.noise_normalize_tab)
        self.noise_percentile_max_label.setObjectName(u"noise_percentile_max_label")
        sizePolicy3.setHeightForWidth(self.noise_percentile_max_label.sizePolicy().hasHeightForWidth())
        self.noise_percentile_max_label.setSizePolicy(sizePolicy3)
        self.noise_percentile_max_label.setMinimumSize(QSize(100, 0))
        self.noise_percentile_max_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.noise_percentile_max_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_14.addWidget(self.noise_percentile_max_label, 2, 0, 1, 1)

        self.noise_percentile_max_slider = QSlider(self.noise_normalize_tab)
        self.noise_percentile_max_slider.setObjectName(u"noise_percentile_max_slider")
        sizePolicy2.setHeightForWidth(self.noise_percentile_max_slider.sizePolicy().hasHeightForWidth())
        self.noise_percentile_max_slider.setSizePolicy(sizePolicy2)
        self.noise_percentile_max_slider.setMinimumSize(QSize(255, 0))
        self.noise_percentile_max_slider.setMinimum(1)
        self.noise_percentile_max_slider.setValue(99)
        self.noise_percentile_max_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_14.addWidget(self.noise_percentile_max_slider, 2, 1, 1, 1)

        self.noise_percentile_max_spin = QSpinBox(self.noise_normalize_tab)
        self.noise_percentile_max_spin.setObjectName(u"noise_percentile_max_spin")
        sizePolicy3.setHeightForWidth(self.noise_percentile_max_spin.sizePolicy().hasHeightForWidth())
        self.noise_percentile_max_spin.setSizePolicy(sizePolicy3)
        self.noise_percentile_max_spin.setMinimumSize(QSize(100, 0))
        self.noise_percentile_max_spin.setFont(font)
        self.noise_percentile_max_spin.setMinimum(1)
        self.noise_percentile_max_spin.setValue(99)

        self.gridLayout_14.addWidget(self.noise_percentile_max_spin, 2, 2, 1, 1)

        self.edge_detection_tabs.addTab(self.noise_normalize_tab, "")
        self.noise_contrast_tab = QWidget()
        self.noise_contrast_tab.setObjectName(u"noise_contrast_tab")
        self.gridLayout_15 = QGridLayout(self.noise_contrast_tab)
        self.gridLayout_15.setObjectName(u"gridLayout_15")
        self.top_hat_kernel_label = QLabel(self.noise_contrast_tab)
        self.top_hat_kernel_label.setObjectName(u"top_hat_kernel_label")
        sizePolicy3.setHeightForWidth(self.top_hat_kernel_label.sizePolicy().hasHeightForWidth())
        self.top_hat_kernel_label.setSizePolicy(sizePolicy3)
        self.top_hat_kernel_label.setMinimumSize(QSize(100, 0))
        self.top_hat_kernel_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.top_hat_kernel_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_15.addWidget(self.top_hat_kernel_label, 0, 0, 1, 1)

        self.top_hat_kernel_slider = QSlider(self.noise_contrast_tab)
        self.top_hat_kernel_slider.setObjectName(u"top_hat_kernel_slider")
        sizePolicy4.setHeightForWidth(self.top_hat_kernel_slider.sizePolicy().hasHeightForWidth())
        self.top_hat_kernel_slider.setSizePolicy(sizePolicy4)
        self.top_hat_kernel_slider.setMinimumSize(QSize(255, 0))
        self.top_hat_kernel_slider.setMinimum(1)
        self.top_hat_kernel_slider.setMaximum(200)
        self.top_hat_kernel_slider.setSingleStep(1)
        self.top_hat_kernel_slider.setValue(21)
        self.top_hat_kernel_slider.setOrientation(Qt.Orientation.Horizontal)
        self.top_hat_kernel_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.top_hat_kernel_slider.setTickInterval(0)

        self.gridLayout_15.addWidget(self.top_hat_kernel_slider, 0, 1, 1, 1)

        self.top_hat_kernel_spin = QSpinBox(self.noise_contrast_tab)
        self.top_hat_kernel_spin.setObjectName(u"top_hat_kernel_spin")
        sizePolicy3.setHeightForWidth(self.top_hat_kernel_spin.sizePolicy().hasHeightForWidth())
        self.top_hat_kernel_spin.setSizePolicy(sizePolicy3)
        self.top_hat_kernel_spin.setMinimumSize(QSize(100, 0))
        self.top_hat_kernel_spin.setFont(font)
        self.top_hat_kernel_spin.setMinimum(1)
        self.top_hat_kernel_spin.setMaximum(200)
        self.top_hat_kernel_spin.setSingleStep(1)
        self.top_hat_kernel_spin.setValue(21)

        self.gridLayout_15.addWidget(self.top_hat_kernel_spin, 0, 2, 1, 1)

        self.clahe_grid_size_label = QLabel(self.noise_contrast_tab)
        self.clahe_grid_size_label.setObjectName(u"clahe_grid_size_label")
        sizePolicy3.setHeightForWidth(self.clahe_grid_size_label.sizePolicy().hasHeightForWidth())
        self.clahe_grid_size_label.setSizePolicy(sizePolicy3)
        self.clahe_grid_size_label.setMinimumSize(QSize(100, 0))
        self.clahe_grid_size_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.clahe_grid_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_15.addWidget(self.clahe_grid_size_label, 1, 0, 1, 1)

        self.clahe_grid_size_slider = QSlider(self.noise_contrast_tab)
        self.clahe_grid_size_slider.setObjectName(u"clahe_grid_size_slider")
        sizePolicy4.setHeightForWidth(self.clahe_grid_size_slider.sizePolicy().hasHeightForWidth())
        self.clahe_grid_size_slider.setSizePolicy(sizePolicy4)
        self.clahe_grid_size_slider.setMinimumSize(QSize(255, 0))
        self.clahe_grid_size_slider.setMinimum(1)
        self.clahe_grid_size_slider.setMaximum(200)
        self.clahe_grid_size_slider.setSingleStep(1)
        self.clahe_grid_size_slider.setValue(8)
        self.clahe_grid_size_slider.setOrientation(Qt.Orientation.Horizontal)
        self.clahe_grid_size_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.clahe_grid_size_slider.setTickInterval(0)

        self.gridLayout_15.addWidget(self.clahe_grid_size_slider, 1, 1, 1, 1)

        self.clahe_grid_size_spin = QSpinBox(self.noise_contrast_tab)
        self.clahe_grid_size_spin.setObjectName(u"clahe_grid_size_spin")
        sizePolicy3.setHeightForWidth(self.clahe_grid_size_spin.sizePolicy().hasHeightForWidth())
        self.clahe_grid_size_spin.setSizePolicy(sizePolicy3)
        self.clahe_grid_size_spin.setMinimumSize(QSize(100, 0))
        self.clahe_grid_size_spin.setFont(font)
        self.clahe_grid_size_spin.setMinimum(1)
        self.clahe_grid_size_spin.setMaximum(200)
        self.clahe_grid_size_spin.setSingleStep(1)
        self.clahe_grid_size_spin.setValue(8)

        self.gridLayout_15.addWidget(self.clahe_grid_size_spin, 1, 2, 1, 1)

        self.clahe_clip_limit_label = QLabel(self.noise_contrast_tab)
        self.clahe_clip_limit_label.setObjectName(u"clahe_clip_limit_label")
        sizePolicy3.setHeightForWidth(self.clahe_clip_limit_label.sizePolicy().hasHeightForWidth())
        self.clahe_clip_limit_label.setSizePolicy(sizePolicy3)
        self.clahe_clip_limit_label.setMinimumSize(QSize(100, 0))
        self.clahe_clip_limit_label.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.clahe_clip_limit_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_15.addWidget(self.clahe_clip_limit_label, 2, 0, 1, 1)

        self.clahe_clip_limit_slider = QSlider(self.noise_contrast_tab)
        self.clahe_clip_limit_slider.setObjectName(u"clahe_clip_limit_slider")
        sizePolicy2.setHeightForWidth(self.clahe_clip_limit_slider.sizePolicy().hasHeightForWidth())
        self.clahe_clip_limit_slider.setSizePolicy(sizePolicy2)
        self.clahe_clip_limit_slider.setMinimumSize(QSize(255, 0))
        self.clahe_clip_limit_slider.setMinimum(10)
        self.clahe_clip_limit_slider.setMaximum(100)
        self.clahe_clip_limit_slider.setValue(25)
        self.clahe_clip_limit_slider.setOrientation(Qt.Orientation.Horizontal)
        self.clahe_clip_limit_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.clahe_clip_limit_slider.setTickInterval(0)

        self.gridLayout_15.addWidget(self.clahe_clip_limit_slider, 2, 1, 1, 1)

        self.clahe_clip_limit_spin = QDoubleSpinBox(self.noise_contrast_tab)
        self.clahe_clip_limit_spin.setObjectName(u"clahe_clip_limit_spin")
        sizePolicy3.setHeightForWidth(self.clahe_clip_limit_spin.sizePolicy().hasHeightForWidth())
        self.clahe_clip_limit_spin.setSizePolicy(sizePolicy3)
        self.clahe_clip_limit_spin.setMinimumSize(QSize(100, 0))
        self.clahe_clip_limit_spin.setFont(font)
        self.clahe_clip_limit_spin.setMinimum(0.000000000000000)
        self.clahe_clip_limit_spin.setMaximum(180.000000000000000)
        self.clahe_clip_limit_spin.setValue(2.500000000000000)

        self.gridLayout_15.addWidget(self.clahe_clip_limit_spin, 2, 2, 1, 1)

        self.edge_detection_tabs.addTab(self.noise_contrast_tab, "")

        self.gridLayout_3.addWidget(self.edge_detection_tabs, 3, 0, 1, 4)


        self.gridLayout_2.addWidget(self.edge_detection_frame, 1, 3, 1, 1)

        self.image_import_frame = QFrame(featureFinder)
        self.image_import_frame.setObjectName(u"image_import_frame")
        sizePolicy1.setHeightForWidth(self.image_import_frame.sizePolicy().hasHeightForWidth())
        self.image_import_frame.setSizePolicy(sizePolicy1)
        self.image_import_frame.setMaximumSize(QSize(1000, 125))
        self.image_import_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.image_import_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_4 = QGridLayout(self.image_import_frame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.image_paths_header = QLabel(self.image_import_frame)
        self.image_paths_header.setObjectName(u"image_paths_header")
        sizePolicy1.setHeightForWidth(self.image_paths_header.sizePolicy().hasHeightForWidth())
        self.image_paths_header.setSizePolicy(sizePolicy1)
        self.image_paths_header.setFont(font1)
        self.image_paths_header.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.image_paths_header, 1, 0, 1, 4)

        self.file_path_label = QLabel(self.image_import_frame)
        self.file_path_label.setObjectName(u"file_path_label")
        sizePolicy1.setHeightForWidth(self.file_path_label.sizePolicy().hasHeightForWidth())
        self.file_path_label.setSizePolicy(sizePolicy1)
        self.file_path_label.setMinimumSize(QSize(100, 0))
        self.file_path_label.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.file_path_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.file_path_label, 2, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.save_status_label = QLabel(self.image_import_frame)
        self.save_status_label.setObjectName(u"save_status_label")
        sizePolicy6.setHeightForWidth(self.save_status_label.sizePolicy().hasHeightForWidth())
        self.save_status_label.setSizePolicy(sizePolicy6)
        self.save_status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.save_status_label, 3, 2, 1, 1)

        self.file_path_browse_button = QPushButton(self.image_import_frame)
        self.file_path_browse_button.setObjectName(u"file_path_browse_button")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.file_path_browse_button.sizePolicy().hasHeightForWidth())
        self.file_path_browse_button.setSizePolicy(sizePolicy7)
        self.file_path_browse_button.setMinimumSize(QSize(0, 0))
        self.file_path_browse_button.setMaximumSize(QSize(32, 16777215))
        self.file_path_browse_button.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))
        self.file_path_browse_button.setAutoFillBackground(False)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderOpen))
        self.file_path_browse_button.setIcon(icon)
        self.file_path_browse_button.setIconSize(QSize(16, 16))

        self.gridLayout_4.addWidget(self.file_path_browse_button, 2, 3, 1, 1)

        self.save_image_label = QLabel(self.image_import_frame)
        self.save_image_label.setObjectName(u"save_image_label")
        sizePolicy3.setHeightForWidth(self.save_image_label.sizePolicy().hasHeightForWidth())
        self.save_image_label.setSizePolicy(sizePolicy3)
        self.save_image_label.setMinimumSize(QSize(100, 0))
        self.save_image_label.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.save_image_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.save_image_label, 3, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.save_image_button = QPushButton(self.image_import_frame)
        self.save_image_button.setObjectName(u"save_image_button")
        self.save_image_button.setEnabled(False)
        sizePolicy7.setHeightForWidth(self.save_image_button.sizePolicy().hasHeightForWidth())
        self.save_image_button.setSizePolicy(sizePolicy7)
        self.save_image_button.setCursor(QCursor(Qt.CursorShape.WhatsThisCursor))

        self.gridLayout_4.addWidget(self.save_image_button, 3, 1, 1, 1)

        self.file_path_entry = QLineEdit(self.image_import_frame)
        self.file_path_entry.setObjectName(u"file_path_entry")
        sizePolicy4.setHeightForWidth(self.file_path_entry.sizePolicy().hasHeightForWidth())
        self.file_path_entry.setSizePolicy(sizePolicy4)
        self.file_path_entry.setMinimumSize(QSize(250, 0))
        self.file_path_entry.setMaxLength(2000000000)

        self.gridLayout_4.addWidget(self.file_path_entry, 2, 1, 1, 2)


        self.gridLayout_2.addWidget(self.image_import_frame, 0, 3, 1, 1)


        self.retranslateUi(featureFinder)

        self.fitting_tabs.setCurrentIndex(0)
        self.edge_detection_tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(featureFinder)
    # setupUi

    def retranslateUi(self, featureFinder):
        featureFinder.setWindowTitle(QCoreApplication.translate("featureFinder", u"Feature Finder", None))
#if QT_CONFIG(tooltip)
        self.crosshair_hough_threshold_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_max_slope_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_max_slope_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_hough_threshold_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_hough_threshold_label.setToolTip(QCoreApplication.translate("featureFinder", u"Defines the number of supporting edge points for a shape to be classified as a line.", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_hough_threshold_label.setText(QCoreApplication.translate("featureFinder", u"Hough Treshold:", None))
#if QT_CONFIG(tooltip)
        self.crosshair_max_slope_label.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowed (absolute) slope.", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_max_slope_label.setText(QCoreApplication.translate("featureFinder", u"Slope Tilt:", None))
#if QT_CONFIG(tooltip)
        self.crosshair_min_length_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_min_length_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_min_length_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable line length.", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_min_length_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Length:", None))
#if QT_CONFIG(tooltip)
        self.crosshair_distance_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum distance allowed between detected features.", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_distance_label.setText(QCoreApplication.translate("featureFinder", u"Distance Interval:", None))
#if QT_CONFIG(tooltip)
        self.crosshair_distance_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_distance_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.fitting_tabs.setTabText(self.fitting_tabs.indexOf(self.crosshair_tab), QCoreApplication.translate("featureFinder", u"Crosshair", None))
#if QT_CONFIG(tooltip)
        self.circularity_label.setToolTip(QCoreApplication.translate("featureFinder", u"A circularity closer to 1 means the blob must be more perfectly round for fitting.", None))
#endif // QT_CONFIG(tooltip)
        self.circularity_label.setText(QCoreApplication.translate("featureFinder", u"Circularity:", None))
#if QT_CONFIG(tooltip)
        self.circularity_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.circularity_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.elliptical_min_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable circular feature size.", None))
#endif // QT_CONFIG(tooltip)
        self.elliptical_min_size_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Area:", None))
#if QT_CONFIG(tooltip)
        self.elliptical_min_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.elliptical_min_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.elliptical_max_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable circular feature size.", None))
#endif // QT_CONFIG(tooltip)
        self.elliptical_max_size_label.setText(QCoreApplication.translate("featureFinder", u"Maximum Area:", None))
#if QT_CONFIG(tooltip)
        self.elliptical_max_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.elliptical_max_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.fitting_tabs.setTabText(self.fitting_tabs.indexOf(self.elliptical_tab), QCoreApplication.translate("featureFinder", u"Elliptical", None))
#if QT_CONFIG(tooltip)
        self.rect_min_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable rectangular feature size.", None))
#endif // QT_CONFIG(tooltip)
        self.rect_min_size_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Area:", None))
#if QT_CONFIG(tooltip)
        self.rect_min_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.rect_min_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.rect_max_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable rectangular feature size.", None))
#endif // QT_CONFIG(tooltip)
        self.rect_max_size_label.setText(QCoreApplication.translate("featureFinder", u"Maximum Area:", None))
#if QT_CONFIG(tooltip)
        self.rect_max_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.rect_max_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.fitting_tabs.setTabText(self.fitting_tabs.indexOf(self.rect_tab), QCoreApplication.translate("featureFinder", u"Rectangular", None))
#if QT_CONFIG(tooltip)
        self.arch_u_score_label.setToolTip(QCoreApplication.translate("featureFinder", u"A U-score closer to 1 means the blob must be more perfectly arched for fitting.", None))
#endif // QT_CONFIG(tooltip)
        self.arch_u_score_label.setText(QCoreApplication.translate("featureFinder", u"U-Score:", None))
#if QT_CONFIG(tooltip)
        self.arch_u_score_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.arch_u_score_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.arch_min_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable circular feature size.", None))
#endif // QT_CONFIG(tooltip)
        self.arch_min_size_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Area:", None))
#if QT_CONFIG(tooltip)
        self.arch_min_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.arch_min_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.arch_max_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable circular feature size.", None))
#endif // QT_CONFIG(tooltip)
        self.arch_max_size_label.setText(QCoreApplication.translate("featureFinder", u"Maximum Area:", None))
#if QT_CONFIG(tooltip)
        self.arch_max_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.arch_max_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.fitting_tabs.setTabText(self.fitting_tabs.indexOf(self.arch_tab), QCoreApplication.translate("featureFinder", u"Arch", None))
        self.feature_fitting_header.setText(QCoreApplication.translate("featureFinder", u"Feature Fitting", None))
#if QT_CONFIG(tooltip)
        self.rect_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting rectangular shapes to found blobs.", None))
#endif // QT_CONFIG(tooltip)
        self.rect_fit_check.setText(QCoreApplication.translate("featureFinder", u"Rectangular Fitting", None))
#if QT_CONFIG(tooltip)
        self.arch_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting arched shapes to found blobs.", None))
#endif // QT_CONFIG(tooltip)
        self.arch_fit_check.setText(QCoreApplication.translate("featureFinder", u"Arch Fitting", None))
#if QT_CONFIG(tooltip)
        self.elliptical_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting circular/elliptical shapes to found blobs.", None))
#endif // QT_CONFIG(tooltip)
        self.elliptical_fit_check.setText(QCoreApplication.translate("featureFinder", u"Elliptical Fitting", None))
#if QT_CONFIG(tooltip)
        self.crosshair_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting crosshair shapes to found lines.", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_fit_check.setText(QCoreApplication.translate("featureFinder", u"Crosshair Fitting", None))
#if QT_CONFIG(tooltip)
        self.canny_edge_check.setToolTip(QCoreApplication.translate("featureFinder", u"Apply Canny edging which will focus on structure rather than pattern.", None))
#endif // QT_CONFIG(tooltip)
        self.canny_edge_check.setText(QCoreApplication.translate("featureFinder", u"Use Canny Edge", None))
        self.edge_detection_header.setText(QCoreApplication.translate("featureFinder", u"Edge Detection", None))
#if QT_CONFIG(tooltip)
        self.show_processed_image_check.setToolTip(QCoreApplication.translate("featureFinder", u"When enabled, this will show the processed image rather than the original image.", None))
#endif // QT_CONFIG(tooltip)
        self.show_processed_image_check.setText(QCoreApplication.translate("featureFinder", u"Show Processed Image", None))
#if QT_CONFIG(tooltip)
        self.invert_image_check.setToolTip(QCoreApplication.translate("featureFinder", u"Invert image which will flip feature focus.", None))
#endif // QT_CONFIG(tooltip)
        self.invert_image_check.setText(QCoreApplication.translate("featureFinder", u"Invert Image", None))
#if QT_CONFIG(tooltip)
        self.reduce_noise_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for applying noise reduction.", None))
#endif // QT_CONFIG(tooltip)
        self.reduce_noise_check.setText(QCoreApplication.translate("featureFinder", u"Reduce Noise", None))
#if QT_CONFIG(tooltip)
        self.gauss_blur_label.setToolTip(QCoreApplication.translate("featureFinder", u"Increasing the Gaussian blur kernel size will reduce noise, but decrease edge accuracy.", None))
#endif // QT_CONFIG(tooltip)
        self.gauss_blur_label.setText(QCoreApplication.translate("featureFinder", u"Gaussian Blur:", None))
#if QT_CONFIG(tooltip)
        self.feature_max_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_max_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.gauss_blur_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_min_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pixel_threshold_label.setToolTip(QCoreApplication.translate("featureFinder", u"Every pixel with intensity \u2265 threshold is set to 255 (white) and every pixel below is set to 0 (black).", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.pixel_threshold_label.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.pixel_threshold_label.setText(QCoreApplication.translate("featureFinder", u"Pixel Threshold:", None))
#if QT_CONFIG(tooltip)
        self.pixel_threshold_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_min_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable blob size used for filtering out detections.", None))
#endif // QT_CONFIG(tooltip)
        self.feature_min_size_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Area:", None))
#if QT_CONFIG(tooltip)
        self.gauss_blur_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_max_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable blob size used for filtering out detections.", None))
#endif // QT_CONFIG(tooltip)
        self.feature_max_size_label.setText(QCoreApplication.translate("featureFinder", u"Maximum Area:", None))
#if QT_CONFIG(tooltip)
        self.pixel_threshold_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_min_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.edge_detection_tabs.setTabText(self.edge_detection_tabs.indexOf(self.classic_tab), QCoreApplication.translate("featureFinder", u"Classic", None))
#if QT_CONFIG(tooltip)
        self.canny_min_label.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable blob size used for filtering out detections.", None))
#endif // QT_CONFIG(tooltip)
        self.canny_min_label.setText(QCoreApplication.translate("featureFinder", u"Lower Limit:", None))
#if QT_CONFIG(tooltip)
        self.canny_min_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.canny_min_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.canny_max_label.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable blob size used for filtering out detections.", None))
#endif // QT_CONFIG(tooltip)
        self.canny_max_label.setText(QCoreApplication.translate("featureFinder", u"Upper Limit:", None))
#if QT_CONFIG(tooltip)
        self.canny_max_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.canny_max_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.edge_detection_tabs.setTabText(self.edge_detection_tabs.indexOf(self.canny_tab), QCoreApplication.translate("featureFinder", u"Canny Edge", None))
#if QT_CONFIG(tooltip)
        self.winsor_percentile_label.setToolTip(QCoreApplication.translate("featureFinder", u"Caps very bright pixels at the specified percentile.", None))
#endif // QT_CONFIG(tooltip)
        self.winsor_percentile_label.setText(QCoreApplication.translate("featureFinder", u"Winsor Percentile:", None))
#if QT_CONFIG(tooltip)
        self.noise_percentile_min_label.setToolTip(QCoreApplication.translate("featureFinder", u"Lower normalization cutoff as percentile.", None))
#endif // QT_CONFIG(tooltip)
        self.noise_percentile_min_label.setText(QCoreApplication.translate("featureFinder", u"Lower Cutoff:", None))
#if QT_CONFIG(tooltip)
        self.noise_percentile_max_label.setToolTip(QCoreApplication.translate("featureFinder", u"Upper  normalization cutoff as percentile.", None))
#endif // QT_CONFIG(tooltip)
        self.noise_percentile_max_label.setText(QCoreApplication.translate("featureFinder", u"Upper Cutoff:", None))
        self.edge_detection_tabs.setTabText(self.edge_detection_tabs.indexOf(self.noise_normalize_tab), QCoreApplication.translate("featureFinder", u"Normalization", None))
#if QT_CONFIG(tooltip)
        self.top_hat_kernel_label.setToolTip(QCoreApplication.translate("featureFinder", u"Emphasizes bright thin-ish features on dark background.", None))
#endif // QT_CONFIG(tooltip)
        self.top_hat_kernel_label.setText(QCoreApplication.translate("featureFinder", u"Top Hat Kernel:", None))
#if QT_CONFIG(tooltip)
        self.top_hat_kernel_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.top_hat_kernel_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.clahe_grid_size_label.setToolTip(QCoreApplication.translate("featureFinder", u"Contrast kernel/grid size for CLAHE equalization.", None))
#endif // QT_CONFIG(tooltip)
        self.clahe_grid_size_label.setText(QCoreApplication.translate("featureFinder", u"CLAHE Grid:", None))
#if QT_CONFIG(tooltip)
        self.clahe_grid_size_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.clahe_grid_size_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.clahe_clip_limit_label.setToolTip(QCoreApplication.translate("featureFinder", u"Contrast clip limit for CLAHE equalization.", None))
#endif // QT_CONFIG(tooltip)
        self.clahe_clip_limit_label.setText(QCoreApplication.translate("featureFinder", u"CLAHE Clip:", None))
#if QT_CONFIG(tooltip)
        self.clahe_clip_limit_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.clahe_clip_limit_spin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.edge_detection_tabs.setTabText(self.edge_detection_tabs.indexOf(self.noise_contrast_tab), QCoreApplication.translate("featureFinder", u"Contrast Boost", None))
        self.image_paths_header.setText(QCoreApplication.translate("featureFinder", u"Image Import/Export", None))
#if QT_CONFIG(tooltip)
        self.file_path_label.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.file_path_label.setText(QCoreApplication.translate("featureFinder", u"Input File Path:", None))
        self.save_status_label.setText("")
#if QT_CONFIG(tooltip)
        self.file_path_browse_button.setToolTip(QCoreApplication.translate("featureFinder", u"File browser for image path selection.", None))
#endif // QT_CONFIG(tooltip)
        self.file_path_browse_button.setText("")
        self.save_image_label.setText(QCoreApplication.translate("featureFinder", u"Export Drawing:", None))
#if QT_CONFIG(tooltip)
        self.save_image_button.setToolTip(QCoreApplication.translate("featureFinder", u"Save the displayed image and data to the provided directory.", None))
#endif // QT_CONFIG(tooltip)
        self.save_image_button.setText(QCoreApplication.translate("featureFinder", u"Save to File...", None))
#if QT_CONFIG(tooltip)
        self.file_path_entry.setToolTip(QCoreApplication.translate("featureFinder", u"Enter or select a image path to start detection.", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

