# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QGraphicsView, QGridLayout, QLabel, QPushButton,
    QSizePolicy, QSlider, QSpacerItem, QSpinBox,
    QTabWidget, QTextEdit, QWidget)

class Ui_featureFinder(object):
    def setupUi(self, featureFinder):
        if not featureFinder.objectName():
            featureFinder.setObjectName(u"featureFinder")
        featureFinder.resize(1004, 585)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(featureFinder.sizePolicy().hasHeightForWidth())
        featureFinder.setSizePolicy(sizePolicy)
        featureFinder.setMinimumSize(QSize(0, 0))
        featureFinder.setMaximumSize(QSize(16777215, 16777215))
        self.gridLayout_2 = QGridLayout(featureFinder)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.image_import_frame = QFrame(featureFinder)
        self.image_import_frame.setObjectName(u"image_import_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.image_import_frame.sizePolicy().hasHeightForWidth())
        self.image_import_frame.setSizePolicy(sizePolicy1)
        self.image_import_frame.setMaximumSize(QSize(1000, 125))
        self.image_import_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.image_import_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_4 = QGridLayout(self.image_import_frame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.file_path_label = QLabel(self.image_import_frame)
        self.file_path_label.setObjectName(u"file_path_label")
        sizePolicy1.setHeightForWidth(self.file_path_label.sizePolicy().hasHeightForWidth())
        self.file_path_label.setSizePolicy(sizePolicy1)
        self.file_path_label.setMinimumSize(QSize(100, 0))
        self.file_path_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.file_path_label, 2, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.save_status_label = QLabel(self.image_import_frame)
        self.save_status_label.setObjectName(u"save_status_label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.save_status_label.sizePolicy().hasHeightForWidth())
        self.save_status_label.setSizePolicy(sizePolicy2)
        self.save_status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.save_status_label, 3, 2, 1, 1)

        self.image_paths_header = QLabel(self.image_import_frame)
        self.image_paths_header.setObjectName(u"image_paths_header")
        sizePolicy1.setHeightForWidth(self.image_paths_header.sizePolicy().hasHeightForWidth())
        self.image_paths_header.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.image_paths_header.setFont(font)
        self.image_paths_header.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.image_paths_header, 1, 0, 1, 4)

        self.save_image_label = QLabel(self.image_import_frame)
        self.save_image_label.setObjectName(u"save_image_label")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.save_image_label.sizePolicy().hasHeightForWidth())
        self.save_image_label.setSizePolicy(sizePolicy3)
        self.save_image_label.setMinimumSize(QSize(100, 0))
        self.save_image_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.save_image_label, 3, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.file_path_entry = QTextEdit(self.image_import_frame)
        self.file_path_entry.setObjectName(u"file_path_entry")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.file_path_entry.sizePolicy().hasHeightForWidth())
        self.file_path_entry.setSizePolicy(sizePolicy4)
        self.file_path_entry.setMinimumSize(QSize(250, 0))
        self.file_path_entry.setMaximumSize(QSize(16777215, 35))
        self.file_path_entry.setFrameShape(QFrame.Shape.StyledPanel)
        self.file_path_entry.setFrameShadow(QFrame.Shadow.Plain)
        self.file_path_entry.setLineWidth(1)
        self.file_path_entry.setMidLineWidth(0)
        self.file_path_entry.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.file_path_entry.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.file_path_entry.setLineWrapMode(QTextEdit.LineWrapMode.NoWrap)

        self.gridLayout_4.addWidget(self.file_path_entry, 2, 1, 1, 2)

        self.save_image_button = QPushButton(self.image_import_frame)
        self.save_image_button.setObjectName(u"save_image_button")
        self.save_image_button.setEnabled(False)
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.save_image_button.sizePolicy().hasHeightForWidth())
        self.save_image_button.setSizePolicy(sizePolicy5)

        self.gridLayout_4.addWidget(self.save_image_button, 3, 1, 1, 1)

        self.file_path_browse_button = QPushButton(self.image_import_frame)
        self.file_path_browse_button.setObjectName(u"file_path_browse_button")
        sizePolicy5.setHeightForWidth(self.file_path_browse_button.sizePolicy().hasHeightForWidth())
        self.file_path_browse_button.setSizePolicy(sizePolicy5)
        self.file_path_browse_button.setMinimumSize(QSize(0, 0))
        self.file_path_browse_button.setMaximumSize(QSize(32, 16777215))
        self.file_path_browse_button.setAutoFillBackground(False)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderOpen))
        self.file_path_browse_button.setIcon(icon)
        self.file_path_browse_button.setIconSize(QSize(16, 16))

        self.gridLayout_4.addWidget(self.file_path_browse_button, 2, 3, 1, 1)


        self.gridLayout_2.addWidget(self.image_import_frame, 0, 3, 1, 1)

        self.fitting_frame = QFrame(featureFinder)
        self.fitting_frame.setObjectName(u"fitting_frame")
        self.fitting_frame.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.fitting_frame.sizePolicy().hasHeightForWidth())
        self.fitting_frame.setSizePolicy(sizePolicy1)
        self.fitting_frame.setMaximumSize(QSize(1000, 16777215))
        self.fitting_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.fitting_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout = QGridLayout(self.fitting_frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.rectangle_fit_check = QCheckBox(self.fitting_frame)
        self.rectangle_fit_check.setObjectName(u"rectangle_fit_check")

        self.gridLayout.addWidget(self.rectangle_fit_check, 1, 0, 1, 1)

        self.fitting_tabs = QTabWidget(self.fitting_frame)
        self.fitting_tabs.setObjectName(u"fitting_tabs")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.fitting_tabs.sizePolicy().hasHeightForWidth())
        self.fitting_tabs.setSizePolicy(sizePolicy6)
        self.circular_tab = QWidget()
        self.circular_tab.setObjectName(u"circular_tab")
        self.circular_tab.setEnabled(False)
        self.gridLayout_5 = QGridLayout(self.circular_tab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.blob_circularity_label = QLabel(self.circular_tab)
        self.blob_circularity_label.setObjectName(u"blob_circularity_label")
        sizePolicy3.setHeightForWidth(self.blob_circularity_label.sizePolicy().hasHeightForWidth())
        self.blob_circularity_label.setSizePolicy(sizePolicy3)
        self.blob_circularity_label.setMinimumSize(QSize(100, 0))
        self.blob_circularity_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.blob_circularity_label, 0, 0, 1, 1)

        self.blob_circularity_slider = QSlider(self.circular_tab)
        self.blob_circularity_slider.setObjectName(u"blob_circularity_slider")
        sizePolicy4.setHeightForWidth(self.blob_circularity_slider.sizePolicy().hasHeightForWidth())
        self.blob_circularity_slider.setSizePolicy(sizePolicy4)
        self.blob_circularity_slider.setMinimumSize(QSize(250, 0))
        self.blob_circularity_slider.setMinimum(10)
        self.blob_circularity_slider.setMaximum(100)
        self.blob_circularity_slider.setSingleStep(1)
        self.blob_circularity_slider.setOrientation(Qt.Orientation.Horizontal)
        self.blob_circularity_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.blob_circularity_slider.setTickInterval(0)

        self.gridLayout_5.addWidget(self.blob_circularity_slider, 0, 1, 1, 1)

        self.blob_circularity_spin = QDoubleSpinBox(self.circular_tab)
        self.blob_circularity_spin.setObjectName(u"blob_circularity_spin")
        sizePolicy3.setHeightForWidth(self.blob_circularity_spin.sizePolicy().hasHeightForWidth())
        self.blob_circularity_spin.setSizePolicy(sizePolicy3)
        self.blob_circularity_spin.setMinimumSize(QSize(100, 0))
        self.blob_circularity_spin.setMinimum(0.100000000000000)
        self.blob_circularity_spin.setMaximum(1.000000000000000)
        self.blob_circularity_spin.setSingleStep(0.100000000000000)

        self.gridLayout_5.addWidget(self.blob_circularity_spin, 0, 2, 1, 1)

        self.blob_min_size_label = QLabel(self.circular_tab)
        self.blob_min_size_label.setObjectName(u"blob_min_size_label")
        sizePolicy3.setHeightForWidth(self.blob_min_size_label.sizePolicy().hasHeightForWidth())
        self.blob_min_size_label.setSizePolicy(sizePolicy3)
        self.blob_min_size_label.setMinimumSize(QSize(100, 0))
        self.blob_min_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.blob_min_size_label, 1, 0, 1, 1)

        self.blob_min_size_slider = QSlider(self.circular_tab)
        self.blob_min_size_slider.setObjectName(u"blob_min_size_slider")
        sizePolicy4.setHeightForWidth(self.blob_min_size_slider.sizePolicy().hasHeightForWidth())
        self.blob_min_size_slider.setSizePolicy(sizePolicy4)
        self.blob_min_size_slider.setMinimumSize(QSize(250, 0))
        self.blob_min_size_slider.setMaximum(100000)
        self.blob_min_size_slider.setSingleStep(100)
        self.blob_min_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_5.addWidget(self.blob_min_size_slider, 1, 1, 1, 1)

        self.blob_min_size_spin = QSpinBox(self.circular_tab)
        self.blob_min_size_spin.setObjectName(u"blob_min_size_spin")
        sizePolicy3.setHeightForWidth(self.blob_min_size_spin.sizePolicy().hasHeightForWidth())
        self.blob_min_size_spin.setSizePolicy(sizePolicy3)
        self.blob_min_size_spin.setMinimumSize(QSize(100, 0))
        self.blob_min_size_spin.setMaximum(100000)
        self.blob_min_size_spin.setSingleStep(100)

        self.gridLayout_5.addWidget(self.blob_min_size_spin, 1, 2, 1, 1)

        self.blob_max_size_label = QLabel(self.circular_tab)
        self.blob_max_size_label.setObjectName(u"blob_max_size_label")
        sizePolicy3.setHeightForWidth(self.blob_max_size_label.sizePolicy().hasHeightForWidth())
        self.blob_max_size_label.setSizePolicy(sizePolicy3)
        self.blob_max_size_label.setMinimumSize(QSize(100, 0))
        self.blob_max_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.blob_max_size_label, 2, 0, 1, 1)

        self.blob_max_size_slider = QSlider(self.circular_tab)
        self.blob_max_size_slider.setObjectName(u"blob_max_size_slider")
        sizePolicy4.setHeightForWidth(self.blob_max_size_slider.sizePolicy().hasHeightForWidth())
        self.blob_max_size_slider.setSizePolicy(sizePolicy4)
        self.blob_max_size_slider.setMinimumSize(QSize(250, 0))
        self.blob_max_size_slider.setMaximum(100000)
        self.blob_max_size_slider.setSingleStep(100)
        self.blob_max_size_slider.setValue(100000)
        self.blob_max_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_5.addWidget(self.blob_max_size_slider, 2, 1, 1, 1)

        self.blob_max_size_spin = QSpinBox(self.circular_tab)
        self.blob_max_size_spin.setObjectName(u"blob_max_size_spin")
        sizePolicy3.setHeightForWidth(self.blob_max_size_spin.sizePolicy().hasHeightForWidth())
        self.blob_max_size_spin.setSizePolicy(sizePolicy3)
        self.blob_max_size_spin.setMinimumSize(QSize(100, 0))
        self.blob_max_size_spin.setMaximum(100000)
        self.blob_max_size_spin.setSingleStep(100)
        self.blob_max_size_spin.setValue(100000)

        self.gridLayout_5.addWidget(self.blob_max_size_spin, 2, 2, 1, 1)

        self.fitting_tabs.addTab(self.circular_tab, "")
        self.crosshair_tab = QWidget()
        self.crosshair_tab.setObjectName(u"crosshair_tab")
        self.crosshair_tab.setEnabled(False)
        self.gridLayout_6 = QGridLayout(self.crosshair_tab)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.hough_threshold_slider = QSlider(self.crosshair_tab)
        self.hough_threshold_slider.setObjectName(u"hough_threshold_slider")
        sizePolicy6.setHeightForWidth(self.hough_threshold_slider.sizePolicy().hasHeightForWidth())
        self.hough_threshold_slider.setSizePolicy(sizePolicy6)
        self.hough_threshold_slider.setMinimumSize(QSize(255, 0))
        self.hough_threshold_slider.setMaximum(255)
        self.hough_threshold_slider.setOrientation(Qt.Orientation.Horizontal)
        self.hough_threshold_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.hough_threshold_slider.setTickInterval(0)

        self.gridLayout_6.addWidget(self.hough_threshold_slider, 0, 2, 1, 1)

        self.crosshair_slope_tilt_spin = QDoubleSpinBox(self.crosshair_tab)
        self.crosshair_slope_tilt_spin.setObjectName(u"crosshair_slope_tilt_spin")
        sizePolicy3.setHeightForWidth(self.crosshair_slope_tilt_spin.sizePolicy().hasHeightForWidth())
        self.crosshair_slope_tilt_spin.setSizePolicy(sizePolicy3)
        self.crosshair_slope_tilt_spin.setMinimumSize(QSize(100, 0))
        self.crosshair_slope_tilt_spin.setMinimum(-180.000000000000000)
        self.crosshair_slope_tilt_spin.setMaximum(180.000000000000000)

        self.gridLayout_6.addWidget(self.crosshair_slope_tilt_spin, 1, 3, 1, 1)

        self.crosshair_slope_tilt_slider = QSlider(self.crosshair_tab)
        self.crosshair_slope_tilt_slider.setObjectName(u"crosshair_slope_tilt_slider")
        sizePolicy6.setHeightForWidth(self.crosshair_slope_tilt_slider.sizePolicy().hasHeightForWidth())
        self.crosshair_slope_tilt_slider.setSizePolicy(sizePolicy6)
        self.crosshair_slope_tilt_slider.setMinimumSize(QSize(255, 0))
        self.crosshair_slope_tilt_slider.setMinimum(-180)
        self.crosshair_slope_tilt_slider.setMaximum(180)
        self.crosshair_slope_tilt_slider.setOrientation(Qt.Orientation.Horizontal)
        self.crosshair_slope_tilt_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.crosshair_slope_tilt_slider.setTickInterval(0)

        self.gridLayout_6.addWidget(self.crosshair_slope_tilt_slider, 1, 2, 1, 1)

        self.hough_threshold_spin = QSpinBox(self.crosshair_tab)
        self.hough_threshold_spin.setObjectName(u"hough_threshold_spin")
        sizePolicy3.setHeightForWidth(self.hough_threshold_spin.sizePolicy().hasHeightForWidth())
        self.hough_threshold_spin.setSizePolicy(sizePolicy3)
        self.hough_threshold_spin.setMinimumSize(QSize(100, 0))
        self.hough_threshold_spin.setMaximum(255)

        self.gridLayout_6.addWidget(self.hough_threshold_spin, 0, 3, 1, 1)

        self.hough_threshold_label = QLabel(self.crosshair_tab)
        self.hough_threshold_label.setObjectName(u"hough_threshold_label")
        sizePolicy3.setHeightForWidth(self.hough_threshold_label.sizePolicy().hasHeightForWidth())
        self.hough_threshold_label.setSizePolicy(sizePolicy3)
        self.hough_threshold_label.setMinimumSize(QSize(100, 0))
        self.hough_threshold_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.hough_threshold_label, 0, 0, 1, 2)

        self.crosshair_slope_tilt_label = QLabel(self.crosshair_tab)
        self.crosshair_slope_tilt_label.setObjectName(u"crosshair_slope_tilt_label")
        sizePolicy3.setHeightForWidth(self.crosshair_slope_tilt_label.sizePolicy().hasHeightForWidth())
        self.crosshair_slope_tilt_label.setSizePolicy(sizePolicy3)
        self.crosshair_slope_tilt_label.setMinimumSize(QSize(100, 0))
        self.crosshair_slope_tilt_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.crosshair_slope_tilt_label, 1, 0, 1, 2)

        self.verticalSpacer = QSpacerItem(20, 5, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout_6.addItem(self.verticalSpacer, 2, 0, 1, 4)

        self.fitting_tabs.addTab(self.crosshair_tab, "")

        self.gridLayout.addWidget(self.fitting_tabs, 4, 0, 1, 2)

        self.crosshair_fit_check = QCheckBox(self.fitting_frame)
        self.crosshair_fit_check.setObjectName(u"crosshair_fit_check")

        self.gridLayout.addWidget(self.crosshair_fit_check, 3, 0, 1, 1)

        self.label = QLabel(self.fitting_frame)
        self.label.setObjectName(u"label")
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        self.label.setFont(font)

        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.circle_fit_check = QCheckBox(self.fitting_frame)
        self.circle_fit_check.setObjectName(u"circle_fit_check")

        self.gridLayout.addWidget(self.circle_fit_check, 2, 0, 1, 1)


        self.gridLayout_2.addWidget(self.fitting_frame, 2, 3, 1, 1)

        self.controls_frame = QFrame(featureFinder)
        self.controls_frame.setObjectName(u"controls_frame")
        self.controls_frame.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.controls_frame.sizePolicy().hasHeightForWidth())
        self.controls_frame.setSizePolicy(sizePolicy1)
        self.controls_frame.setMinimumSize(QSize(0, 0))
        self.controls_frame.setMaximumSize(QSize(1000, 16777215))
        self.controls_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.controls_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_3 = QGridLayout(self.controls_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gauss_blur_spin = QSpinBox(self.controls_frame)
        self.gauss_blur_spin.setObjectName(u"gauss_blur_spin")
        sizePolicy3.setHeightForWidth(self.gauss_blur_spin.sizePolicy().hasHeightForWidth())
        self.gauss_blur_spin.setSizePolicy(sizePolicy3)
        self.gauss_blur_spin.setMinimumSize(QSize(100, 0))
        self.gauss_blur_spin.setMinimum(1)
        self.gauss_blur_spin.setMaximum(200)
        self.gauss_blur_spin.setSingleStep(1)

        self.gridLayout_3.addWidget(self.gauss_blur_spin, 2, 2, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.detection_controls_header = QLabel(self.controls_frame)
        self.detection_controls_header.setObjectName(u"detection_controls_header")
        sizePolicy1.setHeightForWidth(self.detection_controls_header.sizePolicy().hasHeightForWidth())
        self.detection_controls_header.setSizePolicy(sizePolicy1)
        self.detection_controls_header.setFont(font)
        self.detection_controls_header.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_3.addWidget(self.detection_controls_header, 0, 0, 1, 3)

        self.gauss_blur_label = QLabel(self.controls_frame)
        self.gauss_blur_label.setObjectName(u"gauss_blur_label")
        sizePolicy3.setHeightForWidth(self.gauss_blur_label.sizePolicy().hasHeightForWidth())
        self.gauss_blur_label.setSizePolicy(sizePolicy3)
        self.gauss_blur_label.setMinimumSize(QSize(100, 0))
        self.gauss_blur_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_3.addWidget(self.gauss_blur_label, 2, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.feature_min_size_spin = QSpinBox(self.controls_frame)
        self.feature_min_size_spin.setObjectName(u"feature_min_size_spin")
        sizePolicy3.setHeightForWidth(self.feature_min_size_spin.sizePolicy().hasHeightForWidth())
        self.feature_min_size_spin.setSizePolicy(sizePolicy3)
        self.feature_min_size_spin.setMinimumSize(QSize(100, 0))
        self.feature_min_size_spin.setMaximum(100000)
        self.feature_min_size_spin.setSingleStep(100)

        self.gridLayout_3.addWidget(self.feature_min_size_spin, 3, 2, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.pixel_threshold_label = QLabel(self.controls_frame)
        self.pixel_threshold_label.setObjectName(u"pixel_threshold_label")
        sizePolicy3.setHeightForWidth(self.pixel_threshold_label.sizePolicy().hasHeightForWidth())
        self.pixel_threshold_label.setSizePolicy(sizePolicy3)
        self.pixel_threshold_label.setMinimumSize(QSize(100, 0))
        self.pixel_threshold_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_3.addWidget(self.pixel_threshold_label, 1, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.pixel_threshold_slider = QSlider(self.controls_frame)
        self.pixel_threshold_slider.setObjectName(u"pixel_threshold_slider")
        sizePolicy4.setHeightForWidth(self.pixel_threshold_slider.sizePolicy().hasHeightForWidth())
        self.pixel_threshold_slider.setSizePolicy(sizePolicy4)
        self.pixel_threshold_slider.setMinimumSize(QSize(255, 0))
        self.pixel_threshold_slider.setMaximum(255)
        self.pixel_threshold_slider.setSingleStep(1)
        self.pixel_threshold_slider.setOrientation(Qt.Orientation.Horizontal)
        self.pixel_threshold_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.pixel_threshold_slider.setTickInterval(0)

        self.gridLayout_3.addWidget(self.pixel_threshold_slider, 1, 1, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.feature_max_size_spin = QSpinBox(self.controls_frame)
        self.feature_max_size_spin.setObjectName(u"feature_max_size_spin")
        sizePolicy3.setHeightForWidth(self.feature_max_size_spin.sizePolicy().hasHeightForWidth())
        self.feature_max_size_spin.setSizePolicy(sizePolicy3)
        self.feature_max_size_spin.setMinimumSize(QSize(100, 0))
        self.feature_max_size_spin.setMaximum(100000)
        self.feature_max_size_spin.setSingleStep(100)
        self.feature_max_size_spin.setValue(100000)

        self.gridLayout_3.addWidget(self.feature_max_size_spin, 4, 2, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.gauss_blur_slider = QSlider(self.controls_frame)
        self.gauss_blur_slider.setObjectName(u"gauss_blur_slider")
        sizePolicy4.setHeightForWidth(self.gauss_blur_slider.sizePolicy().hasHeightForWidth())
        self.gauss_blur_slider.setSizePolicy(sizePolicy4)
        self.gauss_blur_slider.setMinimumSize(QSize(255, 0))
        self.gauss_blur_slider.setMinimum(1)
        self.gauss_blur_slider.setMaximum(200)
        self.gauss_blur_slider.setSingleStep(1)
        self.gauss_blur_slider.setValue(1)
        self.gauss_blur_slider.setOrientation(Qt.Orientation.Horizontal)
        self.gauss_blur_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        self.gauss_blur_slider.setTickInterval(0)

        self.gridLayout_3.addWidget(self.gauss_blur_slider, 2, 1, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.feature_max_size_slider = QSlider(self.controls_frame)
        self.feature_max_size_slider.setObjectName(u"feature_max_size_slider")
        sizePolicy4.setHeightForWidth(self.feature_max_size_slider.sizePolicy().hasHeightForWidth())
        self.feature_max_size_slider.setSizePolicy(sizePolicy4)
        self.feature_max_size_slider.setMinimumSize(QSize(250, 0))
        self.feature_max_size_slider.setMaximum(100000)
        self.feature_max_size_slider.setSingleStep(100)
        self.feature_max_size_slider.setValue(100000)
        self.feature_max_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_3.addWidget(self.feature_max_size_slider, 4, 1, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.feature_max_size_label = QLabel(self.controls_frame)
        self.feature_max_size_label.setObjectName(u"feature_max_size_label")
        sizePolicy3.setHeightForWidth(self.feature_max_size_label.sizePolicy().hasHeightForWidth())
        self.feature_max_size_label.setSizePolicy(sizePolicy3)
        self.feature_max_size_label.setMinimumSize(QSize(100, 0))
        self.feature_max_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_3.addWidget(self.feature_max_size_label, 4, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.feature_min_size_slider = QSlider(self.controls_frame)
        self.feature_min_size_slider.setObjectName(u"feature_min_size_slider")
        sizePolicy4.setHeightForWidth(self.feature_min_size_slider.sizePolicy().hasHeightForWidth())
        self.feature_min_size_slider.setSizePolicy(sizePolicy4)
        self.feature_min_size_slider.setMinimumSize(QSize(255, 0))
        self.feature_min_size_slider.setMaximum(100000)
        self.feature_min_size_slider.setSingleStep(100)
        self.feature_min_size_slider.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout_3.addWidget(self.feature_min_size_slider, 3, 1, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.feature_min_size_label = QLabel(self.controls_frame)
        self.feature_min_size_label.setObjectName(u"feature_min_size_label")
        sizePolicy3.setHeightForWidth(self.feature_min_size_label.sizePolicy().hasHeightForWidth())
        self.feature_min_size_label.setSizePolicy(sizePolicy3)
        self.feature_min_size_label.setMinimumSize(QSize(100, 0))
        self.feature_min_size_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_3.addWidget(self.feature_min_size_label, 3, 0, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.pixel_threshold_spin = QSpinBox(self.controls_frame)
        self.pixel_threshold_spin.setObjectName(u"pixel_threshold_spin")
        sizePolicy1.setHeightForWidth(self.pixel_threshold_spin.sizePolicy().hasHeightForWidth())
        self.pixel_threshold_spin.setSizePolicy(sizePolicy1)
        self.pixel_threshold_spin.setMinimumSize(QSize(100, 0))
        self.pixel_threshold_spin.setMaximum(255)
        self.pixel_threshold_spin.setSingleStep(1)

        self.gridLayout_3.addWidget(self.pixel_threshold_spin, 1, 2, 1, 1, Qt.AlignmentFlag.AlignVCenter)


        self.gridLayout_2.addWidget(self.controls_frame, 1, 3, 1, 1)

        self.empty_frame = QFrame(featureFinder)
        self.empty_frame.setObjectName(u"empty_frame")
        sizePolicy2.setHeightForWidth(self.empty_frame.sizePolicy().hasHeightForWidth())
        self.empty_frame.setSizePolicy(sizePolicy2)
        self.empty_frame.setMaximumSize(QSize(1000, 16777215))
        self.empty_frame.setFrameShape(QFrame.Shape.NoFrame)
        self.empty_frame.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout_2.addWidget(self.empty_frame, 3, 3, 1, 1)

        self.stream_window = QGraphicsView(featureFinder)
        self.stream_window.setObjectName(u"stream_window")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.stream_window.sizePolicy().hasHeightForWidth())
        self.stream_window.setSizePolicy(sizePolicy7)
        self.stream_window.setMinimumSize(QSize(471, 411))
        self.stream_window.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        self.gridLayout_2.addWidget(self.stream_window, 0, 0, 4, 1)


        self.retranslateUi(featureFinder)

        self.fitting_tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(featureFinder)
    # setupUi

    def retranslateUi(self, featureFinder):
        featureFinder.setWindowTitle(QCoreApplication.translate("featureFinder", u"Feature Finder", None))
        self.file_path_label.setText(QCoreApplication.translate("featureFinder", u"Input File Path:", None))
        self.save_status_label.setText("")
        self.image_paths_header.setText(QCoreApplication.translate("featureFinder", u"Image Import/Export", None))
        self.save_image_label.setText(QCoreApplication.translate("featureFinder", u"Export drawing:", None))
#if QT_CONFIG(tooltip)
        self.file_path_entry.setToolTip(QCoreApplication.translate("featureFinder", u"Path to input image ", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.save_image_button.setToolTip(QCoreApplication.translate("featureFinder", u"Save the displayed image and data to the provided directory", None))
#endif // QT_CONFIG(tooltip)
        self.save_image_button.setText(QCoreApplication.translate("featureFinder", u"Save to File...", None))
#if QT_CONFIG(tooltip)
        self.file_path_browse_button.setToolTip(QCoreApplication.translate("featureFinder", u"<html><head/><body><p>Path browser for input image </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.file_path_browse_button.setText("")
#if QT_CONFIG(tooltip)
        self.rectangle_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting rectangular shape to found contours", None))
#endif // QT_CONFIG(tooltip)
        self.rectangle_fit_check.setText(QCoreApplication.translate("featureFinder", u"Enable Rectangular Fitting", None))
        self.blob_circularity_label.setText(QCoreApplication.translate("featureFinder", u"Circularity:", None))
#if QT_CONFIG(tooltip)
        self.blob_circularity_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Circulairty of passable blobs (1 = perfect circle)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.blob_circularity_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Circulairty of passable blobs (1 = perfect circle)", None))
#endif // QT_CONFIG(tooltip)
        self.blob_min_size_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Size:", None))
#if QT_CONFIG(tooltip)
        self.blob_min_size_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable blob size used for filtering found contours", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.blob_min_size_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable blob size used for filtering found contours", None))
#endif // QT_CONFIG(tooltip)
        self.blob_max_size_label.setText(QCoreApplication.translate("featureFinder", u"Maximum Size:", None))
#if QT_CONFIG(tooltip)
        self.blob_max_size_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable blob size used for filtering found contours", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.blob_max_size_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable blob size used for filtering found contours", None))
#endif // QT_CONFIG(tooltip)
        self.fitting_tabs.setTabText(self.fitting_tabs.indexOf(self.circular_tab), QCoreApplication.translate("featureFinder", u"Circular/Elliptical", None))
#if QT_CONFIG(tooltip)
        self.hough_threshold_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Adjust Hough transform thresholding for line detection", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_slope_tilt_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Rotates definition of horizontal and vertical slope sorting", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.crosshair_slope_tilt_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Rotates definition of horizontal and vertical slope sorting", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.hough_threshold_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Adjust Hough transform thresholding for line detection", None))
#endif // QT_CONFIG(tooltip)
        self.hough_threshold_label.setText(QCoreApplication.translate("featureFinder", u"Hough Treshold:", None))
        self.crosshair_slope_tilt_label.setText(QCoreApplication.translate("featureFinder", u"Slope TIlt:", None))
        self.fitting_tabs.setTabText(self.fitting_tabs.indexOf(self.crosshair_tab), QCoreApplication.translate("featureFinder", u"Crosshair", None))
#if QT_CONFIG(tooltip)
        self.crosshair_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting crosshair shape to found contours", None))
#endif // QT_CONFIG(tooltip)
        self.crosshair_fit_check.setText(QCoreApplication.translate("featureFinder", u"Enable Crossahair Fitting", None))
        self.label.setText(QCoreApplication.translate("featureFinder", u"Feature Fitting", None))
#if QT_CONFIG(tooltip)
        self.circle_fit_check.setToolTip(QCoreApplication.translate("featureFinder", u"Toggle for fitting circular/elliptical shape to found contours", None))
#endif // QT_CONFIG(tooltip)
        self.circle_fit_check.setText(QCoreApplication.translate("featureFinder", u"Enable Ellipse/Circlular Fitting", None))
#if QT_CONFIG(tooltip)
        self.gauss_blur_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Adjust Gaussian blur kernel size to reduce noise for edge detection", None))
#endif // QT_CONFIG(tooltip)
        self.detection_controls_header.setText(QCoreApplication.translate("featureFinder", u"Detection Controls", None))
        self.gauss_blur_label.setText(QCoreApplication.translate("featureFinder", u"Gaussian Blur:", None))
#if QT_CONFIG(tooltip)
        self.feature_min_size_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable contour size used for filtering found edges", None))
#endif // QT_CONFIG(tooltip)
        self.pixel_threshold_label.setText(QCoreApplication.translate("featureFinder", u"Pixel Threshold:", None))
#if QT_CONFIG(tooltip)
        self.pixel_threshold_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Adjust pixel value thresholding for edge detection", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_max_size_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable contour size used for filtering found edges", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.gauss_blur_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Adjust Gaussian blur kernel size to reduce noise for edge detection", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.feature_max_size_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Maximum allowable contour size used for filtering found edges", None))
#endif // QT_CONFIG(tooltip)
        self.feature_max_size_label.setText(QCoreApplication.translate("featureFinder", u"Maximum Size:", None))
#if QT_CONFIG(tooltip)
        self.feature_min_size_slider.setToolTip(QCoreApplication.translate("featureFinder", u"Minimum allowable contour size used for filtering found edges", None))
#endif // QT_CONFIG(tooltip)
        self.feature_min_size_label.setText(QCoreApplication.translate("featureFinder", u"Minimum Size:", None))
#if QT_CONFIG(tooltip)
        self.pixel_threshold_spin.setToolTip(QCoreApplication.translate("featureFinder", u"Adjust pixel value thresholding for edge detection", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

